// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.oppgave;

public class HentOppgaveDto extends OppgaveDto {
    private String id;
    private String status;
    private int versjon;

    public boolean erÅpen() {
        return !"FERDIGSTILT".equalsIgnoreCase(status) && !"FEILREGISTRERT".equalsIgnoreCase(status);
    }

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public int getVersjon() {
        return this.versjon;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.SuppressWarnings("all")
    public void setVersjon(final int versjon) {
        this.versjon = versjon;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof HentOppgaveDto)) return false;
        final HentOppgaveDto other = (HentOppgaveDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getVersjon() != other.getVersjon()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof HentOppgaveDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getVersjon();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "HentOppgaveDto(id=" + this.getId() + ", status=" + this.getStatus() + ", versjon=" + this.getVersjon() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public HentOppgaveDto() {
    }

    @java.lang.SuppressWarnings("all")
    public HentOppgaveDto(final String id, final String status, final int versjon) {
        this.id = id;
        this.status = status;
        this.versjon = versjon;
    }
}
