// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.oppgave;

import java.time.LocalDate;
import java.util.EnumMap;
import java.util.Map;

import com.fasterxml.jackson.annotation.JsonFormat;

public class OppgaveDto {
    private String aktoerId;
    private String tilordnetRessurs;
    private String tema;
    private String oppgavetype;
    private String journalpostId;
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private LocalDate aktivDato;
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private LocalDate fristFerdigstillelse;
    private String prioritet;
    private String saksreferanse;
    private String behandlingstype;
    private String behandlingstema;
    private String temagruppe;
    private String tildeltEnhetsnr;
    private String behandlesAvApplikasjon;
    private String beskrivelse;
    private Map<OppgaveMetadataKey, String> metadata = new EnumMap<>(OppgaveMetadataKey.class);


    @java.lang.SuppressWarnings("all")
    public static class OppgaveDtoBuilder {
        @java.lang.SuppressWarnings("all")
        private String aktoerId;
        @java.lang.SuppressWarnings("all")
        private String tilordnetRessurs;
        @java.lang.SuppressWarnings("all")
        private String tema;
        @java.lang.SuppressWarnings("all")
        private String oppgavetype;
        @java.lang.SuppressWarnings("all")
        private String journalpostId;
        @java.lang.SuppressWarnings("all")
        private LocalDate aktivDato;
        @java.lang.SuppressWarnings("all")
        private LocalDate fristFerdigstillelse;
        @java.lang.SuppressWarnings("all")
        private String prioritet;
        @java.lang.SuppressWarnings("all")
        private String saksreferanse;
        @java.lang.SuppressWarnings("all")
        private String behandlingstype;
        @java.lang.SuppressWarnings("all")
        private String behandlingstema;
        @java.lang.SuppressWarnings("all")
        private String temagruppe;
        @java.lang.SuppressWarnings("all")
        private String tildeltEnhetsnr;
        @java.lang.SuppressWarnings("all")
        private String behandlesAvApplikasjon;
        @java.lang.SuppressWarnings("all")
        private String beskrivelse;
        @java.lang.SuppressWarnings("all")
        private Map<OppgaveMetadataKey, String> metadata;

        @java.lang.SuppressWarnings("all")
        OppgaveDtoBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder aktoerId(final String aktoerId) {
            this.aktoerId = aktoerId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder tilordnetRessurs(final String tilordnetRessurs) {
            this.tilordnetRessurs = tilordnetRessurs;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder tema(final String tema) {
            this.tema = tema;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder oppgavetype(final String oppgavetype) {
            this.oppgavetype = oppgavetype;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder journalpostId(final String journalpostId) {
            this.journalpostId = journalpostId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder aktivDato(final LocalDate aktivDato) {
            this.aktivDato = aktivDato;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder fristFerdigstillelse(final LocalDate fristFerdigstillelse) {
            this.fristFerdigstillelse = fristFerdigstillelse;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder prioritet(final String prioritet) {
            this.prioritet = prioritet;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder saksreferanse(final String saksreferanse) {
            this.saksreferanse = saksreferanse;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder behandlingstype(final String behandlingstype) {
            this.behandlingstype = behandlingstype;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder behandlingstema(final String behandlingstema) {
            this.behandlingstema = behandlingstema;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder temagruppe(final String temagruppe) {
            this.temagruppe = temagruppe;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder tildeltEnhetsnr(final String tildeltEnhetsnr) {
            this.tildeltEnhetsnr = tildeltEnhetsnr;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder behandlesAvApplikasjon(final String behandlesAvApplikasjon) {
            this.behandlesAvApplikasjon = behandlesAvApplikasjon;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder beskrivelse(final String beskrivelse) {
            this.beskrivelse = beskrivelse;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public OppgaveDto.OppgaveDtoBuilder metadata(final Map<OppgaveMetadataKey, String> metadata) {
            this.metadata = metadata;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public OppgaveDto build() {
            return new OppgaveDto(this.aktoerId, this.tilordnetRessurs, this.tema, this.oppgavetype, this.journalpostId, this.aktivDato, this.fristFerdigstillelse, this.prioritet, this.saksreferanse, this.behandlingstype, this.behandlingstema, this.temagruppe, this.tildeltEnhetsnr, this.behandlesAvApplikasjon, this.beskrivelse, this.metadata);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "OppgaveDto.OppgaveDtoBuilder(aktoerId=" + this.aktoerId + ", tilordnetRessurs=" + this.tilordnetRessurs + ", tema=" + this.tema + ", oppgavetype=" + this.oppgavetype + ", journalpostId=" + this.journalpostId + ", aktivDato=" + this.aktivDato + ", fristFerdigstillelse=" + this.fristFerdigstillelse + ", prioritet=" + this.prioritet + ", saksreferanse=" + this.saksreferanse + ", behandlingstype=" + this.behandlingstype + ", behandlingstema=" + this.behandlingstema + ", temagruppe=" + this.temagruppe + ", tildeltEnhetsnr=" + this.tildeltEnhetsnr + ", behandlesAvApplikasjon=" + this.behandlesAvApplikasjon + ", beskrivelse=" + this.beskrivelse + ", metadata=" + this.metadata + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static OppgaveDto.OppgaveDtoBuilder builder() {
        return new OppgaveDto.OppgaveDtoBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getAktoerId() {
        return this.aktoerId;
    }

    @java.lang.SuppressWarnings("all")
    public String getTilordnetRessurs() {
        return this.tilordnetRessurs;
    }

    @java.lang.SuppressWarnings("all")
    public String getTema() {
        return this.tema;
    }

    @java.lang.SuppressWarnings("all")
    public String getOppgavetype() {
        return this.oppgavetype;
    }

    @java.lang.SuppressWarnings("all")
    public String getJournalpostId() {
        return this.journalpostId;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getAktivDato() {
        return this.aktivDato;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getFristFerdigstillelse() {
        return this.fristFerdigstillelse;
    }

    @java.lang.SuppressWarnings("all")
    public String getPrioritet() {
        return this.prioritet;
    }

    @java.lang.SuppressWarnings("all")
    public String getSaksreferanse() {
        return this.saksreferanse;
    }

    @java.lang.SuppressWarnings("all")
    public String getBehandlingstype() {
        return this.behandlingstype;
    }

    @java.lang.SuppressWarnings("all")
    public String getBehandlingstema() {
        return this.behandlingstema;
    }

    @java.lang.SuppressWarnings("all")
    public String getTemagruppe() {
        return this.temagruppe;
    }

    @java.lang.SuppressWarnings("all")
    public String getTildeltEnhetsnr() {
        return this.tildeltEnhetsnr;
    }

    @java.lang.SuppressWarnings("all")
    public String getBehandlesAvApplikasjon() {
        return this.behandlesAvApplikasjon;
    }

    @java.lang.SuppressWarnings("all")
    public String getBeskrivelse() {
        return this.beskrivelse;
    }

    @java.lang.SuppressWarnings("all")
    public Map<OppgaveMetadataKey, String> getMetadata() {
        return this.metadata;
    }

    @java.lang.SuppressWarnings("all")
    public void setAktoerId(final String aktoerId) {
        this.aktoerId = aktoerId;
    }

    @java.lang.SuppressWarnings("all")
    public void setTilordnetRessurs(final String tilordnetRessurs) {
        this.tilordnetRessurs = tilordnetRessurs;
    }

    @java.lang.SuppressWarnings("all")
    public void setTema(final String tema) {
        this.tema = tema;
    }

    @java.lang.SuppressWarnings("all")
    public void setOppgavetype(final String oppgavetype) {
        this.oppgavetype = oppgavetype;
    }

    @java.lang.SuppressWarnings("all")
    public void setJournalpostId(final String journalpostId) {
        this.journalpostId = journalpostId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAktivDato(final LocalDate aktivDato) {
        this.aktivDato = aktivDato;
    }

    @java.lang.SuppressWarnings("all")
    public void setFristFerdigstillelse(final LocalDate fristFerdigstillelse) {
        this.fristFerdigstillelse = fristFerdigstillelse;
    }

    @java.lang.SuppressWarnings("all")
    public void setPrioritet(final String prioritet) {
        this.prioritet = prioritet;
    }

    @java.lang.SuppressWarnings("all")
    public void setSaksreferanse(final String saksreferanse) {
        this.saksreferanse = saksreferanse;
    }

    @java.lang.SuppressWarnings("all")
    public void setBehandlingstype(final String behandlingstype) {
        this.behandlingstype = behandlingstype;
    }

    @java.lang.SuppressWarnings("all")
    public void setBehandlingstema(final String behandlingstema) {
        this.behandlingstema = behandlingstema;
    }

    @java.lang.SuppressWarnings("all")
    public void setTemagruppe(final String temagruppe) {
        this.temagruppe = temagruppe;
    }

    @java.lang.SuppressWarnings("all")
    public void setTildeltEnhetsnr(final String tildeltEnhetsnr) {
        this.tildeltEnhetsnr = tildeltEnhetsnr;
    }

    @java.lang.SuppressWarnings("all")
    public void setBehandlesAvApplikasjon(final String behandlesAvApplikasjon) {
        this.behandlesAvApplikasjon = behandlesAvApplikasjon;
    }

    @java.lang.SuppressWarnings("all")
    public void setBeskrivelse(final String beskrivelse) {
        this.beskrivelse = beskrivelse;
    }

    @java.lang.SuppressWarnings("all")
    public void setMetadata(final Map<OppgaveMetadataKey, String> metadata) {
        this.metadata = metadata;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof OppgaveDto)) return false;
        final OppgaveDto other = (OppgaveDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$aktoerId = this.getAktoerId();
        final java.lang.Object other$aktoerId = other.getAktoerId();
        if (this$aktoerId == null ? other$aktoerId != null : !this$aktoerId.equals(other$aktoerId)) return false;
        final java.lang.Object this$tilordnetRessurs = this.getTilordnetRessurs();
        final java.lang.Object other$tilordnetRessurs = other.getTilordnetRessurs();
        if (this$tilordnetRessurs == null ? other$tilordnetRessurs != null : !this$tilordnetRessurs.equals(other$tilordnetRessurs))
            return false;
        final java.lang.Object this$tema = this.getTema();
        final java.lang.Object other$tema = other.getTema();
        if (this$tema == null ? other$tema != null : !this$tema.equals(other$tema)) return false;
        final java.lang.Object this$oppgavetype = this.getOppgavetype();
        final java.lang.Object other$oppgavetype = other.getOppgavetype();
        if (this$oppgavetype == null ? other$oppgavetype != null : !this$oppgavetype.equals(other$oppgavetype))
            return false;
        final java.lang.Object this$journalpostId = this.getJournalpostId();
        final java.lang.Object other$journalpostId = other.getJournalpostId();
        if (this$journalpostId == null ? other$journalpostId != null : !this$journalpostId.equals(other$journalpostId))
            return false;
        final java.lang.Object this$aktivDato = this.getAktivDato();
        final java.lang.Object other$aktivDato = other.getAktivDato();
        if (this$aktivDato == null ? other$aktivDato != null : !this$aktivDato.equals(other$aktivDato)) return false;
        final java.lang.Object this$fristFerdigstillelse = this.getFristFerdigstillelse();
        final java.lang.Object other$fristFerdigstillelse = other.getFristFerdigstillelse();
        if (this$fristFerdigstillelse == null ? other$fristFerdigstillelse != null : !this$fristFerdigstillelse.equals(other$fristFerdigstillelse))
            return false;
        final java.lang.Object this$prioritet = this.getPrioritet();
        final java.lang.Object other$prioritet = other.getPrioritet();
        if (this$prioritet == null ? other$prioritet != null : !this$prioritet.equals(other$prioritet)) return false;
        final java.lang.Object this$saksreferanse = this.getSaksreferanse();
        final java.lang.Object other$saksreferanse = other.getSaksreferanse();
        if (this$saksreferanse == null ? other$saksreferanse != null : !this$saksreferanse.equals(other$saksreferanse))
            return false;
        final java.lang.Object this$behandlingstype = this.getBehandlingstype();
        final java.lang.Object other$behandlingstype = other.getBehandlingstype();
        if (this$behandlingstype == null ? other$behandlingstype != null : !this$behandlingstype.equals(other$behandlingstype))
            return false;
        final java.lang.Object this$behandlingstema = this.getBehandlingstema();
        final java.lang.Object other$behandlingstema = other.getBehandlingstema();
        if (this$behandlingstema == null ? other$behandlingstema != null : !this$behandlingstema.equals(other$behandlingstema))
            return false;
        final java.lang.Object this$temagruppe = this.getTemagruppe();
        final java.lang.Object other$temagruppe = other.getTemagruppe();
        if (this$temagruppe == null ? other$temagruppe != null : !this$temagruppe.equals(other$temagruppe))
            return false;
        final java.lang.Object this$tildeltEnhetsnr = this.getTildeltEnhetsnr();
        final java.lang.Object other$tildeltEnhetsnr = other.getTildeltEnhetsnr();
        if (this$tildeltEnhetsnr == null ? other$tildeltEnhetsnr != null : !this$tildeltEnhetsnr.equals(other$tildeltEnhetsnr))
            return false;
        final java.lang.Object this$behandlesAvApplikasjon = this.getBehandlesAvApplikasjon();
        final java.lang.Object other$behandlesAvApplikasjon = other.getBehandlesAvApplikasjon();
        if (this$behandlesAvApplikasjon == null ? other$behandlesAvApplikasjon != null : !this$behandlesAvApplikasjon.equals(other$behandlesAvApplikasjon))
            return false;
        final java.lang.Object this$beskrivelse = this.getBeskrivelse();
        final java.lang.Object other$beskrivelse = other.getBeskrivelse();
        if (this$beskrivelse == null ? other$beskrivelse != null : !this$beskrivelse.equals(other$beskrivelse))
            return false;
        final java.lang.Object this$metadata = this.getMetadata();
        final java.lang.Object other$metadata = other.getMetadata();
        if (this$metadata == null ? other$metadata != null : !this$metadata.equals(other$metadata)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof OppgaveDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $aktoerId = this.getAktoerId();
        result = result * PRIME + ($aktoerId == null ? 43 : $aktoerId.hashCode());
        final java.lang.Object $tilordnetRessurs = this.getTilordnetRessurs();
        result = result * PRIME + ($tilordnetRessurs == null ? 43 : $tilordnetRessurs.hashCode());
        final java.lang.Object $tema = this.getTema();
        result = result * PRIME + ($tema == null ? 43 : $tema.hashCode());
        final java.lang.Object $oppgavetype = this.getOppgavetype();
        result = result * PRIME + ($oppgavetype == null ? 43 : $oppgavetype.hashCode());
        final java.lang.Object $journalpostId = this.getJournalpostId();
        result = result * PRIME + ($journalpostId == null ? 43 : $journalpostId.hashCode());
        final java.lang.Object $aktivDato = this.getAktivDato();
        result = result * PRIME + ($aktivDato == null ? 43 : $aktivDato.hashCode());
        final java.lang.Object $fristFerdigstillelse = this.getFristFerdigstillelse();
        result = result * PRIME + ($fristFerdigstillelse == null ? 43 : $fristFerdigstillelse.hashCode());
        final java.lang.Object $prioritet = this.getPrioritet();
        result = result * PRIME + ($prioritet == null ? 43 : $prioritet.hashCode());
        final java.lang.Object $saksreferanse = this.getSaksreferanse();
        result = result * PRIME + ($saksreferanse == null ? 43 : $saksreferanse.hashCode());
        final java.lang.Object $behandlingstype = this.getBehandlingstype();
        result = result * PRIME + ($behandlingstype == null ? 43 : $behandlingstype.hashCode());
        final java.lang.Object $behandlingstema = this.getBehandlingstema();
        result = result * PRIME + ($behandlingstema == null ? 43 : $behandlingstema.hashCode());
        final java.lang.Object $temagruppe = this.getTemagruppe();
        result = result * PRIME + ($temagruppe == null ? 43 : $temagruppe.hashCode());
        final java.lang.Object $tildeltEnhetsnr = this.getTildeltEnhetsnr();
        result = result * PRIME + ($tildeltEnhetsnr == null ? 43 : $tildeltEnhetsnr.hashCode());
        final java.lang.Object $behandlesAvApplikasjon = this.getBehandlesAvApplikasjon();
        result = result * PRIME + ($behandlesAvApplikasjon == null ? 43 : $behandlesAvApplikasjon.hashCode());
        final java.lang.Object $beskrivelse = this.getBeskrivelse();
        result = result * PRIME + ($beskrivelse == null ? 43 : $beskrivelse.hashCode());
        final java.lang.Object $metadata = this.getMetadata();
        result = result * PRIME + ($metadata == null ? 43 : $metadata.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "OppgaveDto(aktoerId=" + this.getAktoerId() + ", tilordnetRessurs=" + this.getTilordnetRessurs() + ", tema=" + this.getTema() + ", oppgavetype=" + this.getOppgavetype() + ", journalpostId=" + this.getJournalpostId() + ", aktivDato=" + this.getAktivDato() + ", fristFerdigstillelse=" + this.getFristFerdigstillelse() + ", prioritet=" + this.getPrioritet() + ", saksreferanse=" + this.getSaksreferanse() + ", behandlingstype=" + this.getBehandlingstype() + ", behandlingstema=" + this.getBehandlingstema() + ", temagruppe=" + this.getTemagruppe() + ", tildeltEnhetsnr=" + this.getTildeltEnhetsnr() + ", behandlesAvApplikasjon=" + this.getBehandlesAvApplikasjon() + ", metadata=" + this.getMetadata() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public OppgaveDto(final String aktoerId, final String tilordnetRessurs, final String tema, final String oppgavetype, final String journalpostId, final LocalDate aktivDato, final LocalDate fristFerdigstillelse, final String prioritet, final String saksreferanse, final String behandlingstype, final String behandlingstema, final String temagruppe, final String tildeltEnhetsnr, final String behandlesAvApplikasjon, final String beskrivelse, final Map<OppgaveMetadataKey, String> metadata) {
        this.aktoerId = aktoerId;
        this.tilordnetRessurs = tilordnetRessurs;
        this.tema = tema;
        this.oppgavetype = oppgavetype;
        this.journalpostId = journalpostId;
        this.aktivDato = aktivDato;
        this.fristFerdigstillelse = fristFerdigstillelse;
        this.prioritet = prioritet;
        this.saksreferanse = saksreferanse;
        this.behandlingstype = behandlingstype;
        this.behandlingstema = behandlingstema;
        this.temagruppe = temagruppe;
        this.tildeltEnhetsnr = tildeltEnhetsnr;
        this.behandlesAvApplikasjon = behandlesAvApplikasjon;
        this.beskrivelse = beskrivelse;
        this.metadata = metadata;
    }

    @java.lang.SuppressWarnings("all")
    public OppgaveDto() {
    }
}
