package no.nav.melosys.eessi.service.sed.helpers

enum class EøsLandkoder(val value: String) {
    BE("Belgia"),
    BG("Bulgaria"),
    DK("Danmark"),
    EE("Estland"),
    FI("Finland"),
    FR("Frankrike"),
    FO("Færøyene"),
    GL("Grønland"),
    GR("Hellas"),
    IE("Irland"),
    IS("Island"),
    IT("Italia"),
    HR("Kroatia"),
    CY("Kypros"),
    LV("Latvia"),
    LI("Liechtenstein"),
    LT("Litauen"),
    LU("Luxembourg"),
    MT("Malta"),
    NL("Nederland"),
    NO("Norge"),
    PL("Polen"),
    PT("Portugal"),
    RO("Romania"),
    SK("Slovakia"),
    SI("Slovenia"),
    ES("Spania"),
    GB("Storbritannia"),
    SJ("Svalbard og Jan Mayen"),
    CH("Sveits"),
    SE("Sverige"),
    CZ("Tsjekkia"),
    DE("Tyskland"),
    HU("Ungarn"),
    AT("Østerrike"),
    AX("Åland")
}

