// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.saf.dto;

public class SafResponse {
    private SafJournalpost query;

    @java.lang.SuppressWarnings("all")
    public SafResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public SafJournalpost getQuery() {
        return this.query;
    }

    @java.lang.SuppressWarnings("all")
    public void setQuery(final SafJournalpost query) {
        this.query = query;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SafResponse)) return false;
        final SafResponse other = (SafResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$query = this.getQuery();
        final java.lang.Object other$query = other.getQuery();
        if (this$query == null ? other$query != null : !this$query.equals(other$query)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SafResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $query = this.getQuery();
        result = result * PRIME + ($query == null ? 43 : $query.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SafResponse(query=" + this.getQuery() + ")";
    }
}
