// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.saf.dto;

public class Tilleggsopplysning {
    private String nokkel;
    private String verdi;

    @java.lang.SuppressWarnings("all")
    public String getNokkel() {
        return this.nokkel;
    }

    @java.lang.SuppressWarnings("all")
    public String getVerdi() {
        return this.verdi;
    }

    @java.lang.SuppressWarnings("all")
    public void setNokkel(final String nokkel) {
        this.nokkel = nokkel;
    }

    @java.lang.SuppressWarnings("all")
    public void setVerdi(final String verdi) {
        this.verdi = verdi;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Tilleggsopplysning)) return false;
        final Tilleggsopplysning other = (Tilleggsopplysning) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$nokkel = this.getNokkel();
        final java.lang.Object other$nokkel = other.getNokkel();
        if (this$nokkel == null ? other$nokkel != null : !this$nokkel.equals(other$nokkel)) return false;
        final java.lang.Object this$verdi = this.getVerdi();
        final java.lang.Object other$verdi = other.getVerdi();
        if (this$verdi == null ? other$verdi != null : !this$verdi.equals(other$verdi)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Tilleggsopplysning;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $nokkel = this.getNokkel();
        result = result * PRIME + ($nokkel == null ? 43 : $nokkel.hashCode());
        final java.lang.Object $verdi = this.getVerdi();
        result = result * PRIME + ($verdi == null ? 43 : $verdi.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Tilleggsopplysning(nokkel=" + this.getNokkel() + ", verdi=" + this.getVerdi() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Tilleggsopplysning(final String nokkel, final String verdi) {
        this.nokkel = nokkel;
        this.verdi = verdi;
    }

    @java.lang.SuppressWarnings("all")
    public Tilleggsopplysning() {
    }
}
