// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.kafkadlq;

import jakarta.persistence.Column;
import jakarta.persistence.DiscriminatorValue;
import jakarta.persistence.Entity;

import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import no.nav.melosys.eessi.identifisering.OppgaveKafkaAivenRecord;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;

@Entity
@DiscriminatorValue("OPPGAVE_HENDELSE_AIVEN")
public class OppgaveHendelseAivenKafkaDLQ extends KafkaDLQ {
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(name = "melding", columnDefinition = "jsonb")
    private OppgaveKafkaAivenRecord oppgaveEndretHendelse;

    @Override
    public String hentMeldingSomStreng() throws JsonProcessingException {
        ObjectMapper objectMapper = new ObjectMapper();
        objectMapper.registerModule(new JavaTimeModule());
        return objectMapper.writeValueAsString(oppgaveEndretHendelse);
    }

    @java.lang.SuppressWarnings("all")
    public OppgaveKafkaAivenRecord getOppgaveEndretHendelse() {
        return this.oppgaveEndretHendelse;
    }

    @java.lang.SuppressWarnings("all")
    public void setOppgaveEndretHendelse(final OppgaveKafkaAivenRecord oppgaveEndretHendelse) {
        this.oppgaveEndretHendelse = oppgaveEndretHendelse;
    }

    @java.lang.SuppressWarnings("all")
    public OppgaveHendelseAivenKafkaDLQ() {
    }
}
