// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.bucinfo;

public class BucInfo {
    private static final String PROCESS_OWNER = "PO";
    private String applicationRoleId;
    private String id;
    private String processDefinitionId;
    private String status;

    public boolean norgeErCaseOwner() {
        return PROCESS_OWNER.equalsIgnoreCase(applicationRoleId);
    }

    public boolean bucErÅpen() {
        return "open".equalsIgnoreCase(status);
    }

    @java.lang.SuppressWarnings("all")
    public BucInfo() {
    }

    @java.lang.SuppressWarnings("all")
    public String getApplicationRoleId() {
        return this.applicationRoleId;
    }

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getProcessDefinitionId() {
        return this.processDefinitionId;
    }

    @java.lang.SuppressWarnings("all")
    public String getStatus() {
        return this.status;
    }

    @java.lang.SuppressWarnings("all")
    public void setApplicationRoleId(final String applicationRoleId) {
        this.applicationRoleId = applicationRoleId;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setProcessDefinitionId(final String processDefinitionId) {
        this.processDefinitionId = processDefinitionId;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatus(final String status) {
        this.status = status;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BucInfo)) return false;
        final BucInfo other = (BucInfo) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$applicationRoleId = this.getApplicationRoleId();
        final java.lang.Object other$applicationRoleId = other.getApplicationRoleId();
        if (this$applicationRoleId == null ? other$applicationRoleId != null : !this$applicationRoleId.equals(other$applicationRoleId))
            return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$processDefinitionId = this.getProcessDefinitionId();
        final java.lang.Object other$processDefinitionId = other.getProcessDefinitionId();
        if (this$processDefinitionId == null ? other$processDefinitionId != null : !this$processDefinitionId.equals(other$processDefinitionId))
            return false;
        final java.lang.Object this$status = this.getStatus();
        final java.lang.Object other$status = other.getStatus();
        if (this$status == null ? other$status != null : !this$status.equals(other$status)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BucInfo;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $applicationRoleId = this.getApplicationRoleId();
        result = result * PRIME + ($applicationRoleId == null ? 43 : $applicationRoleId.hashCode());
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $processDefinitionId = this.getProcessDefinitionId();
        result = result * PRIME + ($processDefinitionId == null ? 43 : $processDefinitionId.hashCode());
        final java.lang.Object $status = this.getStatus();
        result = result * PRIME + ($status == null ? 43 : $status.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "BucInfo(applicationRoleId=" + this.getApplicationRoleId() + ", id=" + this.getId() + ", processDefinitionId=" + this.getProcessDefinitionId() + ", status=" + this.getStatus() + ")";
    }
}
