FROM navikt/java:12
LABEL maintainer="Team Melosys"

ARG JAR_FILE
RUN echo $JAR_FILE
COPY melosys-eessi-app/target/$JAR_FILE /app/app.jar

ARG SPRING_PROFILES
RUN echo $SPRING_PROFILES
ENV SPRING_PROFILES_ACTIVE $SPRING_PROFILES