apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: melosys-eessi
  namespace: @@NAMESPACE@@
  labels:
    team: teammelosys
spec:
  image: repo.adeo.no:5443/melosys/melosys-eessi:@@IMAGE_VERSION@@
  port: 8080
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/health
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/health
    initialDelay: 60
    timeout: 10
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  vault:
    enabled: true
  prometheus:
    enabled: true
    path: /internal/prometheus
  ingresses:
  - "https://@@URL@@"
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: nais
