apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: melosys-eessi
  namespace: @@NAMESPACE@@
  labels:
    team: teammelosys
spec:
  image: docker.adeo.no:5000/melosys/melosys-eessi:@@RELEASE_VERSION@@
  port: 8080
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  liveness:
    path: /api/actuator/health
    initialDelay: 60
    timeout: 10
  readiness:
    path: /api/actuator/health
    initialDelay: 60
    timeout: 10
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 50m
      memory: 512Mi
  vault:
    enabled: true
  ingresses:
  - "https://melosys-eessi@@URL_NAMESPACE@@.nais.preprod.local"