// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Arbeidsgiver {
    private Adresse adresse;
    private List<Identifikator> identifikator;
    private String navn;

    @java.lang.SuppressWarnings("all")
    public Arbeidsgiver() {
    }

    @java.lang.SuppressWarnings("all")
    public Adresse getAdresse() {
        return this.adresse;
    }

    @java.lang.SuppressWarnings("all")
    public List<Identifikator> getIdentifikator() {
        return this.identifikator;
    }

    @java.lang.SuppressWarnings("all")
    public String getNavn() {
        return this.navn;
    }

    @java.lang.SuppressWarnings("all")
    public void setAdresse(final Adresse adresse) {
        this.adresse = adresse;
    }

    @java.lang.SuppressWarnings("all")
    public void setIdentifikator(final List<Identifikator> identifikator) {
        this.identifikator = identifikator;
    }

    @java.lang.SuppressWarnings("all")
    public void setNavn(final String navn) {
        this.navn = navn;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Arbeidsgiver)) return false;
        final Arbeidsgiver other = (Arbeidsgiver) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$adresse = this.getAdresse();
        final java.lang.Object other$adresse = other.getAdresse();
        if (this$adresse == null ? other$adresse != null : !this$adresse.equals(other$adresse)) return false;
        final java.lang.Object this$identifikator = this.getIdentifikator();
        final java.lang.Object other$identifikator = other.getIdentifikator();
        if (this$identifikator == null ? other$identifikator != null : !this$identifikator.equals(other$identifikator)) return false;
        final java.lang.Object this$navn = this.getNavn();
        final java.lang.Object other$navn = other.getNavn();
        if (this$navn == null ? other$navn != null : !this$navn.equals(other$navn)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Arbeidsgiver;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $adresse = this.getAdresse();
        result = result * PRIME + ($adresse == null ? 43 : $adresse.hashCode());
        final java.lang.Object $identifikator = this.getIdentifikator();
        result = result * PRIME + ($identifikator == null ? 43 : $identifikator.hashCode());
        final java.lang.Object $navn = this.getNavn();
        result = result * PRIME + ($navn == null ? 43 : $navn.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Arbeidsgiver(adresse=" + this.getAdresse() + ", identifikator=" + this.getIdentifikator() + ", navn=" + this.getNavn() + ")";
    }
}
