// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ArbeidIFlereLand {
    private Bosted bosted;
    private Yrkesaktivitet yrkesaktivitet;

    @java.lang.SuppressWarnings("all")
    public ArbeidIFlereLand() {
    }

    @java.lang.SuppressWarnings("all")
    public Bosted getBosted() {
        return this.bosted;
    }

    @java.lang.SuppressWarnings("all")
    public Yrkesaktivitet getYrkesaktivitet() {
        return this.yrkesaktivitet;
    }

    @java.lang.SuppressWarnings("all")
    public void setBosted(final Bosted bosted) {
        this.bosted = bosted;
    }

    @java.lang.SuppressWarnings("all")
    public void setYrkesaktivitet(final Yrkesaktivitet yrkesaktivitet) {
        this.yrkesaktivitet = yrkesaktivitet;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ArbeidIFlereLand)) return false;
        final ArbeidIFlereLand other = (ArbeidIFlereLand) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$bosted = this.getBosted();
        final java.lang.Object other$bosted = other.getBosted();
        if (this$bosted == null ? other$bosted != null : !this$bosted.equals(other$bosted)) return false;
        final java.lang.Object this$yrkesaktivitet = this.getYrkesaktivitet();
        final java.lang.Object other$yrkesaktivitet = other.getYrkesaktivitet();
        if (this$yrkesaktivitet == null ? other$yrkesaktivitet != null : !this$yrkesaktivitet.equals(other$yrkesaktivitet))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ArbeidIFlereLand;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $bosted = this.getBosted();
        result = result * PRIME + ($bosted == null ? 43 : $bosted.hashCode());
        final java.lang.Object $yrkesaktivitet = this.getYrkesaktivitet();
        result = result * PRIME + ($yrkesaktivitet == null ? 43 : $yrkesaktivitet.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ArbeidIFlereLand(bosted=" + this.getBosted() + ", yrkesaktivitet=" + this.getYrkesaktivitet() + ")";
    }
}
