// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Avslutning {
    private String dato;
    private Aarsak aarsak;
    private String type;

    @java.lang.SuppressWarnings("all")
    public Avslutning() {
    }

    @java.lang.SuppressWarnings("all")
    public String getDato() {
        return this.dato;
    }

    @java.lang.SuppressWarnings("all")
    public Aarsak getAarsak() {
        return this.aarsak;
    }

    @java.lang.SuppressWarnings("all")
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public void setDato(final String dato) {
        this.dato = dato;
    }

    @java.lang.SuppressWarnings("all")
    public void setAarsak(final Aarsak aarsak) {
        this.aarsak = aarsak;
    }

    @java.lang.SuppressWarnings("all")
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Avslutning)) return false;
        final Avslutning other = (Avslutning) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$dato = this.getDato();
        final java.lang.Object other$dato = other.getDato();
        if (this$dato == null ? other$dato != null : !this$dato.equals(other$dato)) return false;
        final java.lang.Object this$aarsak = this.getAarsak();
        final java.lang.Object other$aarsak = other.getAarsak();
        if (this$aarsak == null ? other$aarsak != null : !this$aarsak.equals(other$aarsak)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Avslutning;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $dato = this.getDato();
        result = result * PRIME + ($dato == null ? 43 : $dato.hashCode());
        final java.lang.Object $aarsak = this.getAarsak();
        result = result * PRIME + ($aarsak == null ? 43 : $aarsak.hashCode());
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Avslutning(dato=" + this.getDato() + ", aarsak=" + this.getAarsak() + ", type=" + this.getType() + ")";
    }
}
