// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class Avslag {
    private String erbehovformerinformasjon;
    private Land forslagformedlemskap;
    private String begrunnelse;

    @java.lang.SuppressWarnings("all")
    public Avslag() {
    }

    @java.lang.SuppressWarnings("all")
    public String getErbehovformerinformasjon() {
        return this.erbehovformerinformasjon;
    }

    @java.lang.SuppressWarnings("all")
    public Land getForslagformedlemskap() {
        return this.forslagformedlemskap;
    }

    @java.lang.SuppressWarnings("all")
    public String getBegrunnelse() {
        return this.begrunnelse;
    }

    @java.lang.SuppressWarnings("all")
    public void setErbehovformerinformasjon(final String erbehovformerinformasjon) {
        this.erbehovformerinformasjon = erbehovformerinformasjon;
    }

    @java.lang.SuppressWarnings("all")
    public void setForslagformedlemskap(final Land forslagformedlemskap) {
        this.forslagformedlemskap = forslagformedlemskap;
    }

    @java.lang.SuppressWarnings("all")
    public void setBegrunnelse(final String begrunnelse) {
        this.begrunnelse = begrunnelse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Avslag)) return false;
        final Avslag other = (Avslag) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$erbehovformerinformasjon = this.getErbehovformerinformasjon();
        final java.lang.Object other$erbehovformerinformasjon = other.getErbehovformerinformasjon();
        if (this$erbehovformerinformasjon == null ? other$erbehovformerinformasjon != null : !this$erbehovformerinformasjon.equals(other$erbehovformerinformasjon))
            return false;
        final java.lang.Object this$forslagformedlemskap = this.getForslagformedlemskap();
        final java.lang.Object other$forslagformedlemskap = other.getForslagformedlemskap();
        if (this$forslagformedlemskap == null ? other$forslagformedlemskap != null : !this$forslagformedlemskap.equals(other$forslagformedlemskap))
            return false;
        final java.lang.Object this$begrunnelse = this.getBegrunnelse();
        final java.lang.Object other$begrunnelse = other.getBegrunnelse();
        if (this$begrunnelse == null ? other$begrunnelse != null : !this$begrunnelse.equals(other$begrunnelse))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Avslag;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $erbehovformerinformasjon = this.getErbehovformerinformasjon();
        result = result * PRIME + ($erbehovformerinformasjon == null ? 43 : $erbehovformerinformasjon.hashCode());
        final java.lang.Object $forslagformedlemskap = this.getForslagformedlemskap();
        result = result * PRIME + ($forslagformedlemskap == null ? 43 : $forslagformedlemskap.hashCode());
        final java.lang.Object $begrunnelse = this.getBegrunnelse();
        result = result * PRIME + ($begrunnelse == null ? 43 : $begrunnelse.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Avslag(erbehovformerinformasjon=" + this.getErbehovformerinformasjon() + ", forslagformedlemskap=" + this.getForslagformedlemskap() + ", begrunnelse=" + this.getBegrunnelse() + ")";
    }
}
