// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Far {
    private Person person;

    @java.lang.SuppressWarnings("all")
    public Far() {
    }

    @java.lang.SuppressWarnings("all")
    public Person getPerson() {
        return this.person;
    }

    @java.lang.SuppressWarnings("all")
    public void setPerson(final Person person) {
        this.person = person;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Far)) return false;
        final Far other = (Far) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$person = this.getPerson();
        final java.lang.Object other$person = other.getPerson();
        if (this$person == null ? other$person != null : !this$person.equals(other$person)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Far;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $person = this.getPerson();
        result = result * PRIME + ($person == null ? 43 : $person.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Far(person=" + this.getPerson() + ")";
    }
}
