// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Fastperiode {
    private String sluttdato;
    private String startdato;

    @java.lang.SuppressWarnings("all")
    public Fastperiode() {
    }

    @java.lang.SuppressWarnings("all")
    public String getSluttdato() {
        return this.sluttdato;
    }

    @java.lang.SuppressWarnings("all")
    public String getStartdato() {
        return this.startdato;
    }

    @java.lang.SuppressWarnings("all")
    public void setSluttdato(final String sluttdato) {
        this.sluttdato = sluttdato;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartdato(final String startdato) {
        this.startdato = startdato;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Fastperiode)) return false;
        final Fastperiode other = (Fastperiode) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$sluttdato = this.getSluttdato();
        final java.lang.Object other$sluttdato = other.getSluttdato();
        if (this$sluttdato == null ? other$sluttdato != null : !this$sluttdato.equals(other$sluttdato)) return false;
        final java.lang.Object this$startdato = this.getStartdato();
        final java.lang.Object other$startdato = other.getStartdato();
        if (this$startdato == null ? other$startdato != null : !this$startdato.equals(other$startdato)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Fastperiode;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $sluttdato = this.getSluttdato();
        result = result * PRIME + ($sluttdato == null ? 43 : $sluttdato.hashCode());
        final java.lang.Object $startdato = this.getStartdato();
        result = result * PRIME + ($startdato == null ? 43 : $startdato.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Fastperiode(sluttdato=" + this.getSluttdato() + ", startdato=" + this.getStartdato() + ")";
    }
}
