// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Foedested {
    private String by;
    private String land;
    private String region;

    @java.lang.SuppressWarnings("all")
    public Foedested() {
    }

    @java.lang.SuppressWarnings("all")
    public String getBy() {
        return this.by;
    }

    @java.lang.SuppressWarnings("all")
    public String getLand() {
        return this.land;
    }

    @java.lang.SuppressWarnings("all")
    public String getRegion() {
        return this.region;
    }

    @java.lang.SuppressWarnings("all")
    public void setBy(final String by) {
        this.by = by;
    }

    @java.lang.SuppressWarnings("all")
    public void setLand(final String land) {
        this.land = land;
    }

    @java.lang.SuppressWarnings("all")
    public void setRegion(final String region) {
        this.region = region;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Foedested)) return false;
        final Foedested other = (Foedested) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$by = this.getBy();
        final java.lang.Object other$by = other.getBy();
        if (this$by == null ? other$by != null : !this$by.equals(other$by)) return false;
        final java.lang.Object this$land = this.getLand();
        final java.lang.Object other$land = other.getLand();
        if (this$land == null ? other$land != null : !this$land.equals(other$land)) return false;
        final java.lang.Object this$region = this.getRegion();
        final java.lang.Object other$region = other.getRegion();
        if (this$region == null ? other$region != null : !this$region.equals(other$region)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Foedested;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $by = this.getBy();
        result = result * PRIME + ($by == null ? 43 : $by.hashCode());
        final java.lang.Object $land = this.getLand();
        result = result * PRIME + ($land == null ? 43 : $land.hashCode());
        final java.lang.Object $region = this.getRegion();
        result = result * PRIME + ($region == null ? 43 : $region.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Foedested(by=" + this.getBy() + ", land=" + this.getLand() + ", region=" + this.getRegion() + ")";
    }
}
