// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class ForrigeSoeknad {
    private String dato;

    @java.lang.SuppressWarnings("all")
    public ForrigeSoeknad() {
    }

    @java.lang.SuppressWarnings("all")
    public String getDato() {
        return this.dato;
    }

    @java.lang.SuppressWarnings("all")
    public void setDato(final String dato) {
        this.dato = dato;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof ForrigeSoeknad)) return false;
        final ForrigeSoeknad other = (ForrigeSoeknad) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$dato = this.getDato();
        final java.lang.Object other$dato = other.getDato();
        if (this$dato == null ? other$dato != null : !this$dato.equals(other$dato)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof ForrigeSoeknad;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $dato = this.getDato();
        result = result * PRIME + ($dato == null ? 43 : $dato.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "ForrigeSoeknad(dato=" + this.getDato() + ")";
    }
}
