// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Grunnlag {
    private String annet;
    private String artikkel;

    @java.lang.SuppressWarnings("all")
    public Grunnlag() {
    }

    @java.lang.SuppressWarnings("all")
    public String getAnnet() {
        return this.annet;
    }

    @java.lang.SuppressWarnings("all")
    public String getArtikkel() {
        return this.artikkel;
    }

    @java.lang.SuppressWarnings("all")
    public void setAnnet(final String annet) {
        this.annet = annet;
    }

    @java.lang.SuppressWarnings("all")
    public void setArtikkel(final String artikkel) {
        this.artikkel = artikkel;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Grunnlag)) return false;
        final Grunnlag other = (Grunnlag) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$annet = this.getAnnet();
        final java.lang.Object other$annet = other.getAnnet();
        if (this$annet == null ? other$annet != null : !this$annet.equals(other$annet)) return false;
        final java.lang.Object this$artikkel = this.getArtikkel();
        final java.lang.Object other$artikkel = other.getArtikkel();
        if (this$artikkel == null ? other$artikkel != null : !this$artikkel.equals(other$artikkel)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Grunnlag;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $annet = this.getAnnet();
        result = result * PRIME + ($annet == null ? 43 : $annet.hashCode());
        final java.lang.Object $artikkel = this.getArtikkel();
        result = result * PRIME + ($artikkel == null ? 43 : $artikkel.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Grunnlag(annet=" + this.getAnnet() + ", artikkel=" + this.getArtikkel() + ")";
    }
}
