// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import com.fasterxml.jackson.annotation.JsonInclude;

@JsonInclude(JsonInclude.Include.NON_NULL)
public class Grunn {
    private String type;
    //Annet settes kun dersom type = 99
    private String annet;

    @java.lang.SuppressWarnings("all")
    public Grunn() {
    }

    @java.lang.SuppressWarnings("all")
    public Grunn(final String type, final String annet) {
        this.type = type;
        this.annet = annet;
    }

    @java.lang.SuppressWarnings("all")
    public String getType() {
        return this.type;
    }

    @java.lang.SuppressWarnings("all")
    public String getAnnet() {
        return this.annet;
    }

    @java.lang.SuppressWarnings("all")
    public void setType(final String type) {
        this.type = type;
    }

    @java.lang.SuppressWarnings("all")
    public void setAnnet(final String annet) {
        this.annet = annet;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Grunn)) return false;
        final Grunn other = (Grunn) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$type = this.getType();
        final java.lang.Object other$type = other.getType();
        if (this$type == null ? other$type != null : !this$type.equals(other$type)) return false;
        final java.lang.Object this$annet = this.getAnnet();
        final java.lang.Object other$annet = other.getAnnet();
        if (this$annet == null ? other$annet != null : !this$annet.equals(other$annet)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Grunn;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $type = this.getType();
        result = result * PRIME + ($type == null ? 43 : $type.hashCode());
        final java.lang.Object $annet = this.getAnnet();
        result = result * PRIME + ($annet == null ? 43 : $annet.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Grunn(type=" + this.getType() + ", annet=" + this.getAnnet() + ")";
    }
}
