// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import no.nav.melosys.eessi.models.sed.ArbeidsgiverDeserializer;

@JsonInclude(Include.NON_NULL)
@JsonIgnoreProperties(ignoreUnknown = true)
public class Nav {
    private List<Arbeidssted> arbeidssted;
    private List<Arbeidsland> arbeidsland;
    private String harfastarbeidssted;
    private Bruker bruker;
    private Selvstendig selvstendig;
    private String ytterligereinformasjon;
    //Kan forekomme som et enkelt objekt ved feks H001
    @JsonDeserialize(using = ArbeidsgiverDeserializer.class)
    private List<Arbeidsgiver> arbeidsgiver;
    //Kun for X001, X006 og X008
    private Sak sak;
    private EessiSak eessisak;

    @java.lang.SuppressWarnings("all")
    public Nav() {
    }

    @java.lang.SuppressWarnings("all")
    public List<Arbeidssted> getArbeidssted() {
        return this.arbeidssted;
    }

    @java.lang.SuppressWarnings("all")
    public List<Arbeidsland> getArbeidsland() {
        return this.arbeidsland;
    }

    @java.lang.SuppressWarnings("all")
    public String getHarfastarbeidssted() {
        return this.harfastarbeidssted;
    }

    @java.lang.SuppressWarnings("all")
    public Bruker getBruker() {
        return this.bruker;
    }

    @java.lang.SuppressWarnings("all")
    public Selvstendig getSelvstendig() {
        return this.selvstendig;
    }

    @java.lang.SuppressWarnings("all")
    public String getYtterligereinformasjon() {
        return this.ytterligereinformasjon;
    }

    @java.lang.SuppressWarnings("all")
    public List<Arbeidsgiver> getArbeidsgiver() {
        return this.arbeidsgiver;
    }

    @java.lang.SuppressWarnings("all")
    public Sak getSak() {
        return this.sak;
    }

    @java.lang.SuppressWarnings("all")
    public EessiSak getEessisak() {
        return this.eessisak;
    }

    @java.lang.SuppressWarnings("all")
    public void setArbeidssted(final List<Arbeidssted> arbeidssted) {
        this.arbeidssted = arbeidssted;
    }

    @java.lang.SuppressWarnings("all")
    public void setArbeidsland(final List<Arbeidsland> arbeidsland) {
        this.arbeidsland = arbeidsland;
    }

    @java.lang.SuppressWarnings("all")
    public void setHarfastarbeidssted(final String harfastarbeidssted) {
        this.harfastarbeidssted = harfastarbeidssted;
    }

    @java.lang.SuppressWarnings("all")
    public void setBruker(final Bruker bruker) {
        this.bruker = bruker;
    }

    @java.lang.SuppressWarnings("all")
    public void setSelvstendig(final Selvstendig selvstendig) {
        this.selvstendig = selvstendig;
    }

    @java.lang.SuppressWarnings("all")
    public void setYtterligereinformasjon(final String ytterligereinformasjon) {
        this.ytterligereinformasjon = ytterligereinformasjon;
    }

    @JsonDeserialize(using = ArbeidsgiverDeserializer.class)
    @java.lang.SuppressWarnings("all")
    public void setArbeidsgiver(final List<Arbeidsgiver> arbeidsgiver) {
        this.arbeidsgiver = arbeidsgiver;
    }

    @java.lang.SuppressWarnings("all")
    public void setSak(final Sak sak) {
        this.sak = sak;
    }

    @java.lang.SuppressWarnings("all")
    public void setEessisak(final EessiSak eessisak) {
        this.eessisak = eessisak;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Nav)) return false;
        final Nav other = (Nav) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$arbeidssted = this.getArbeidssted();
        final java.lang.Object other$arbeidssted = other.getArbeidssted();
        if (this$arbeidssted == null ? other$arbeidssted != null : !this$arbeidssted.equals(other$arbeidssted))
            return false;
        final java.lang.Object this$arbeidsland = this.getArbeidsland();
        final java.lang.Object other$arbeidsland = other.getArbeidsland();
        if (this$arbeidsland == null ? other$arbeidsland != null : !this$arbeidsland.equals(other$arbeidsland))
            return false;
        final java.lang.Object this$harfastarbeidssted = this.getHarfastarbeidssted();
        final java.lang.Object other$harfastarbeidssted = other.getHarfastarbeidssted();
        if (this$harfastarbeidssted == null ? other$harfastarbeidssted != null : !this$harfastarbeidssted.equals(other$harfastarbeidssted))
            return false;
        final java.lang.Object this$bruker = this.getBruker();
        final java.lang.Object other$bruker = other.getBruker();
        if (this$bruker == null ? other$bruker != null : !this$bruker.equals(other$bruker)) return false;
        final java.lang.Object this$selvstendig = this.getSelvstendig();
        final java.lang.Object other$selvstendig = other.getSelvstendig();
        if (this$selvstendig == null ? other$selvstendig != null : !this$selvstendig.equals(other$selvstendig))
            return false;
        final java.lang.Object this$ytterligereinformasjon = this.getYtterligereinformasjon();
        final java.lang.Object other$ytterligereinformasjon = other.getYtterligereinformasjon();
        if (this$ytterligereinformasjon == null ? other$ytterligereinformasjon != null : !this$ytterligereinformasjon.equals(other$ytterligereinformasjon))
            return false;
        final java.lang.Object this$arbeidsgiver = this.getArbeidsgiver();
        final java.lang.Object other$arbeidsgiver = other.getArbeidsgiver();
        if (this$arbeidsgiver == null ? other$arbeidsgiver != null : !this$arbeidsgiver.equals(other$arbeidsgiver))
            return false;
        final java.lang.Object this$sak = this.getSak();
        final java.lang.Object other$sak = other.getSak();
        if (this$sak == null ? other$sak != null : !this$sak.equals(other$sak)) return false;
        final java.lang.Object this$eessisak = this.getEessisak();
        final java.lang.Object other$eessisak = other.getEessisak();
        if (this$eessisak == null ? other$eessisak != null : !this$eessisak.equals(other$eessisak)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Nav;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $arbeidssted = this.getArbeidssted();
        result = result * PRIME + ($arbeidssted == null ? 43 : $arbeidssted.hashCode());
        final java.lang.Object $arbeidsland = this.getArbeidsland();
        result = result * PRIME + ($arbeidsland == null ? 43 : $arbeidsland.hashCode());
        final java.lang.Object $harfastarbeidssted = this.getHarfastarbeidssted();
        result = result * PRIME + ($harfastarbeidssted == null ? 43 : $harfastarbeidssted.hashCode());
        final java.lang.Object $bruker = this.getBruker();
        result = result * PRIME + ($bruker == null ? 43 : $bruker.hashCode());
        final java.lang.Object $selvstendig = this.getSelvstendig();
        result = result * PRIME + ($selvstendig == null ? 43 : $selvstendig.hashCode());
        final java.lang.Object $ytterligereinformasjon = this.getYtterligereinformasjon();
        result = result * PRIME + ($ytterligereinformasjon == null ? 43 : $ytterligereinformasjon.hashCode());
        final java.lang.Object $arbeidsgiver = this.getArbeidsgiver();
        result = result * PRIME + ($arbeidsgiver == null ? 43 : $arbeidsgiver.hashCode());
        final java.lang.Object $sak = this.getSak();
        result = result * PRIME + ($sak == null ? 43 : $sak.hashCode());
        final java.lang.Object $eessisak = this.getEessisak();
        result = result * PRIME + ($eessisak == null ? 43 : $eessisak.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Nav(arbeidssted=" + this.getArbeidssted() + ", arbeidsland=" + this.getArbeidsland() + ", harfastarbeidssted=" + this.getHarfastarbeidssted() + ", bruker=" + this.getBruker() + ", selvstendig=" + this.getSelvstendig() + ", ytterligereinformasjon=" + this.getYtterligereinformasjon() + ", arbeidsgiver=" + this.getArbeidsgiver() + ", sak=" + this.getSak() + ", eessisak=" + this.getEessisak() + ")";
    }
}
