// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Periode {
    private AapenPeriode aapenperiode;
    private Fastperiode fastperiode;

    public boolean erAapenPeriode() {
        return aapenperiode != null && aapenperiode.getStartdato() != null;
    }

    @java.lang.SuppressWarnings("all")
    public Periode() {
    }

    @java.lang.SuppressWarnings("all")
    public AapenPeriode getAapenperiode() {
        return this.aapenperiode;
    }

    @java.lang.SuppressWarnings("all")
    public Fastperiode getFastperiode() {
        return this.fastperiode;
    }

    @java.lang.SuppressWarnings("all")
    public void setAapenperiode(final AapenPeriode aapenperiode) {
        this.aapenperiode = aapenperiode;
    }

    @java.lang.SuppressWarnings("all")
    public void setFastperiode(final Fastperiode fastperiode) {
        this.fastperiode = fastperiode;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Periode)) return false;
        final Periode other = (Periode) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$aapenperiode = this.getAapenperiode();
        final java.lang.Object other$aapenperiode = other.getAapenperiode();
        if (this$aapenperiode == null ? other$aapenperiode != null : !this$aapenperiode.equals(other$aapenperiode))
            return false;
        final java.lang.Object this$fastperiode = this.getFastperiode();
        final java.lang.Object other$fastperiode = other.getFastperiode();
        if (this$fastperiode == null ? other$fastperiode != null : !this$fastperiode.equals(other$fastperiode))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Periode;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $aapenperiode = this.getAapenperiode();
        result = result * PRIME + ($aapenperiode == null ? 43 : $aapenperiode.hashCode());
        final java.lang.Object $fastperiode = this.getFastperiode();
        result = result * PRIME + ($fastperiode == null ? 43 : $fastperiode.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Periode(aapenperiode=" + this.getAapenperiode() + ", fastperiode=" + this.getFastperiode() + ")";
    }
}
