// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import java.util.Collection;
import java.util.HashSet;
import java.util.Objects;
import java.util.Optional;
import java.util.stream.Collectors;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Person {
    private String etternavn;
    private String etternavnvedfoedsel;
    private Foedested foedested;
    private String foedselsdato;
    private String fornavn;
    private String fornavnvedfoedsel;
    private Kjønn kjoenn;
    private Collection<Pin> pin = new HashSet<>();
    private Collection<Statsborgerskap> statsborgerskap = new HashSet<>();

    public Optional<Pin> finnNorskPin() {
        return pin.stream().filter(p -> "NO".equals(p.getLand())).findFirst();
    }

    public Collection<String> hentStatsborgerksapsliste() {
        return  //Kan av en mystisk grunn inneholde null-felter
            statsborgerskap.stream().filter(Objects::nonNull).map(Statsborgerskap::getLand).collect(Collectors.toSet());
    }

    public boolean harStatsborgerskap(String land) {
        return statsborgerskap.stream().anyMatch(s -> s.getLand().equals(land));
    }

    public Optional<Pin> finnUtenlandskIdFraLand(String land) {
        return pin.stream().filter(p -> p.getLand().equals(land)).findFirst();
    }

    @java.lang.SuppressWarnings("all")
    public Person() {
    }

    @java.lang.SuppressWarnings("all")
    public String getEtternavn() {
        return this.etternavn;
    }

    @java.lang.SuppressWarnings("all")
    public String getEtternavnvedfoedsel() {
        return this.etternavnvedfoedsel;
    }

    @java.lang.SuppressWarnings("all")
    public Foedested getFoedested() {
        return this.foedested;
    }

    @java.lang.SuppressWarnings("all")
    public String getFoedselsdato() {
        return this.foedselsdato;
    }

    @java.lang.SuppressWarnings("all")
    public String getFornavn() {
        return this.fornavn;
    }

    @java.lang.SuppressWarnings("all")
    public String getFornavnvedfoedsel() {
        return this.fornavnvedfoedsel;
    }

    @java.lang.SuppressWarnings("all")
    public Kjønn getKjoenn() {
        return this.kjoenn;
    }

    @java.lang.SuppressWarnings("all")
    public Collection<Pin> getPin() {
        return this.pin;
    }

    @java.lang.SuppressWarnings("all")
    public Collection<Statsborgerskap> getStatsborgerskap() {
        return this.statsborgerskap;
    }

    @java.lang.SuppressWarnings("all")
    public void setEtternavn(final String etternavn) {
        this.etternavn = etternavn;
    }

    @java.lang.SuppressWarnings("all")
    public void setEtternavnvedfoedsel(final String etternavnvedfoedsel) {
        this.etternavnvedfoedsel = etternavnvedfoedsel;
    }

    @java.lang.SuppressWarnings("all")
    public void setFoedested(final Foedested foedested) {
        this.foedested = foedested;
    }

    @java.lang.SuppressWarnings("all")
    public void setFoedselsdato(final String foedselsdato) {
        this.foedselsdato = foedselsdato;
    }

    @java.lang.SuppressWarnings("all")
    public void setFornavn(final String fornavn) {
        this.fornavn = fornavn;
    }

    @java.lang.SuppressWarnings("all")
    public void setFornavnvedfoedsel(final String fornavnvedfoedsel) {
        this.fornavnvedfoedsel = fornavnvedfoedsel;
    }

    @java.lang.SuppressWarnings("all")
    public void setKjoenn(final Kjønn kjoenn) {
        this.kjoenn = kjoenn;
    }

    @java.lang.SuppressWarnings("all")
    public void setPin(final Collection<Pin> pin) {
        this.pin = pin;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatsborgerskap(final Collection<Statsborgerskap> statsborgerskap) {
        this.statsborgerskap = statsborgerskap;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Person)) return false;
        final Person other = (Person) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$etternavn = this.getEtternavn();
        final java.lang.Object other$etternavn = other.getEtternavn();
        if (this$etternavn == null ? other$etternavn != null : !this$etternavn.equals(other$etternavn)) return false;
        final java.lang.Object this$etternavnvedfoedsel = this.getEtternavnvedfoedsel();
        final java.lang.Object other$etternavnvedfoedsel = other.getEtternavnvedfoedsel();
        if (this$etternavnvedfoedsel == null ? other$etternavnvedfoedsel != null : !this$etternavnvedfoedsel.equals(other$etternavnvedfoedsel))
            return false;
        final java.lang.Object this$foedested = this.getFoedested();
        final java.lang.Object other$foedested = other.getFoedested();
        if (this$foedested == null ? other$foedested != null : !this$foedested.equals(other$foedested)) return false;
        final java.lang.Object this$foedselsdato = this.getFoedselsdato();
        final java.lang.Object other$foedselsdato = other.getFoedselsdato();
        if (this$foedselsdato == null ? other$foedselsdato != null : !this$foedselsdato.equals(other$foedselsdato))
            return false;
        final java.lang.Object this$fornavn = this.getFornavn();
        final java.lang.Object other$fornavn = other.getFornavn();
        if (this$fornavn == null ? other$fornavn != null : !this$fornavn.equals(other$fornavn)) return false;
        final java.lang.Object this$fornavnvedfoedsel = this.getFornavnvedfoedsel();
        final java.lang.Object other$fornavnvedfoedsel = other.getFornavnvedfoedsel();
        if (this$fornavnvedfoedsel == null ? other$fornavnvedfoedsel != null : !this$fornavnvedfoedsel.equals(other$fornavnvedfoedsel))
            return false;
        final java.lang.Object this$kjoenn = this.getKjoenn();
        final java.lang.Object other$kjoenn = other.getKjoenn();
        if (this$kjoenn == null ? other$kjoenn != null : !this$kjoenn.equals(other$kjoenn)) return false;
        final java.lang.Object this$pin = this.getPin();
        final java.lang.Object other$pin = other.getPin();
        if (this$pin == null ? other$pin != null : !this$pin.equals(other$pin)) return false;
        final java.lang.Object this$statsborgerskap = this.getStatsborgerskap();
        final java.lang.Object other$statsborgerskap = other.getStatsborgerskap();
        if (this$statsborgerskap == null ? other$statsborgerskap != null : !this$statsborgerskap.equals(other$statsborgerskap))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Person;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $etternavn = this.getEtternavn();
        result = result * PRIME + ($etternavn == null ? 43 : $etternavn.hashCode());
        final java.lang.Object $etternavnvedfoedsel = this.getEtternavnvedfoedsel();
        result = result * PRIME + ($etternavnvedfoedsel == null ? 43 : $etternavnvedfoedsel.hashCode());
        final java.lang.Object $foedested = this.getFoedested();
        result = result * PRIME + ($foedested == null ? 43 : $foedested.hashCode());
        final java.lang.Object $foedselsdato = this.getFoedselsdato();
        result = result * PRIME + ($foedselsdato == null ? 43 : $foedselsdato.hashCode());
        final java.lang.Object $fornavn = this.getFornavn();
        result = result * PRIME + ($fornavn == null ? 43 : $fornavn.hashCode());
        final java.lang.Object $fornavnvedfoedsel = this.getFornavnvedfoedsel();
        result = result * PRIME + ($fornavnvedfoedsel == null ? 43 : $fornavnvedfoedsel.hashCode());
        final java.lang.Object $kjoenn = this.getKjoenn();
        result = result * PRIME + ($kjoenn == null ? 43 : $kjoenn.hashCode());
        final java.lang.Object $pin = this.getPin();
        result = result * PRIME + ($pin == null ? 43 : $pin.hashCode());
        final java.lang.Object $statsborgerskap = this.getStatsborgerskap();
        result = result * PRIME + ($statsborgerskap == null ? 43 : $statsborgerskap.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Person(etternavn=" + this.getEtternavn() + ", etternavnvedfoedsel=" + this.getEtternavnvedfoedsel() + ", foedested=" + this.getFoedested() + ", foedselsdato=" + this.getFoedselsdato() + ", fornavn=" + this.getFornavn() + ", fornavnvedfoedsel=" + this.getFornavnvedfoedsel() + ", kjoenn=" + this.getKjoenn() + ", pin=" + this.getPin() + ", statsborgerskap=" + this.getStatsborgerskap() + ")";
    }
}
