// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Pin {
    public Pin(String identifikator, String land, String sektor) {
        this.identifikator = identifikator;
        this.land = land;
        this.sektor = sektor;
    }

    private String identifikator;
    private String land;
    private String sektor;
    private String institusjonsid;
    private String institusjonsnavn;

    @java.lang.SuppressWarnings("all")
    public String getIdentifikator() {
        return this.identifikator;
    }

    @java.lang.SuppressWarnings("all")
    public String getLand() {
        return this.land;
    }

    @java.lang.SuppressWarnings("all")
    public String getSektor() {
        return this.sektor;
    }

    @java.lang.SuppressWarnings("all")
    public String getInstitusjonsid() {
        return this.institusjonsid;
    }

    @java.lang.SuppressWarnings("all")
    public String getInstitusjonsnavn() {
        return this.institusjonsnavn;
    }

    @java.lang.SuppressWarnings("all")
    public void setIdentifikator(final String identifikator) {
        this.identifikator = identifikator;
    }

    @java.lang.SuppressWarnings("all")
    public void setLand(final String land) {
        this.land = land;
    }

    @java.lang.SuppressWarnings("all")
    public void setSektor(final String sektor) {
        this.sektor = sektor;
    }

    @java.lang.SuppressWarnings("all")
    public void setInstitusjonsid(final String institusjonsid) {
        this.institusjonsid = institusjonsid;
    }

    @java.lang.SuppressWarnings("all")
    public void setInstitusjonsnavn(final String institusjonsnavn) {
        this.institusjonsnavn = institusjonsnavn;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Pin)) return false;
        final Pin other = (Pin) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$identifikator = this.getIdentifikator();
        final java.lang.Object other$identifikator = other.getIdentifikator();
        if (this$identifikator == null ? other$identifikator != null : !this$identifikator.equals(other$identifikator))
            return false;
        final java.lang.Object this$land = this.getLand();
        final java.lang.Object other$land = other.getLand();
        if (this$land == null ? other$land != null : !this$land.equals(other$land)) return false;
        final java.lang.Object this$sektor = this.getSektor();
        final java.lang.Object other$sektor = other.getSektor();
        if (this$sektor == null ? other$sektor != null : !this$sektor.equals(other$sektor)) return false;
        final java.lang.Object this$institusjonsid = this.getInstitusjonsid();
        final java.lang.Object other$institusjonsid = other.getInstitusjonsid();
        if (this$institusjonsid == null ? other$institusjonsid != null : !this$institusjonsid.equals(other$institusjonsid))
            return false;
        final java.lang.Object this$institusjonsnavn = this.getInstitusjonsnavn();
        final java.lang.Object other$institusjonsnavn = other.getInstitusjonsnavn();
        if (this$institusjonsnavn == null ? other$institusjonsnavn != null : !this$institusjonsnavn.equals(other$institusjonsnavn))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Pin;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $identifikator = this.getIdentifikator();
        result = result * PRIME + ($identifikator == null ? 43 : $identifikator.hashCode());
        final java.lang.Object $land = this.getLand();
        result = result * PRIME + ($land == null ? 43 : $land.hashCode());
        final java.lang.Object $sektor = this.getSektor();
        result = result * PRIME + ($sektor == null ? 43 : $sektor.hashCode());
        final java.lang.Object $institusjonsid = this.getInstitusjonsid();
        result = result * PRIME + ($institusjonsid == null ? 43 : $institusjonsid.hashCode());
        final java.lang.Object $institusjonsnavn = this.getInstitusjonsnavn();
        result = result * PRIME + ($institusjonsnavn == null ? 43 : $institusjonsnavn.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Pin(identifikator=" + this.getIdentifikator() + ", land=" + this.getLand() + ", sektor=" + this.getSektor() + ", institusjonsid=" + this.getInstitusjonsid() + ", institusjonsnavn=" + this.getInstitusjonsnavn() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Pin() {
    }

    @java.lang.SuppressWarnings("all")
    public Pin(final String identifikator, final String land, final String sektor, final String institusjonsid, final String institusjonsnavn) {
        this.identifikator = identifikator;
        this.land = land;
        this.sektor = sektor;
        this.institusjonsid = institusjonsid;
        this.institusjonsnavn = institusjonsnavn;
    }
}
