// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonInclude.Include;

@JsonInclude(Include.NON_NULL)
public class Unntak {
    private String startdatoansattforsikret;
    private Grunnlag grunnlag;
    private SpesielleOmstendigheter spesielleomstendigheter;
    private String startdatokontraktansettelse;
    private String begrunnelse;
    private String a1grunnlag;

    @java.lang.SuppressWarnings("all")
    public Unntak() {
    }

    @java.lang.SuppressWarnings("all")
    public String getStartdatoansattforsikret() {
        return this.startdatoansattforsikret;
    }

    @java.lang.SuppressWarnings("all")
    public Grunnlag getGrunnlag() {
        return this.grunnlag;
    }

    @java.lang.SuppressWarnings("all")
    public SpesielleOmstendigheter getSpesielleomstendigheter() {
        return this.spesielleomstendigheter;
    }

    @java.lang.SuppressWarnings("all")
    public String getStartdatokontraktansettelse() {
        return this.startdatokontraktansettelse;
    }

    @java.lang.SuppressWarnings("all")
    public String getBegrunnelse() {
        return this.begrunnelse;
    }

    @java.lang.SuppressWarnings("all")
    public String getA1grunnlag() {
        return this.a1grunnlag;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartdatoansattforsikret(final String startdatoansattforsikret) {
        this.startdatoansattforsikret = startdatoansattforsikret;
    }

    @java.lang.SuppressWarnings("all")
    public void setGrunnlag(final Grunnlag grunnlag) {
        this.grunnlag = grunnlag;
    }

    @java.lang.SuppressWarnings("all")
    public void setSpesielleomstendigheter(final SpesielleOmstendigheter spesielleomstendigheter) {
        this.spesielleomstendigheter = spesielleomstendigheter;
    }

    @java.lang.SuppressWarnings("all")
    public void setStartdatokontraktansettelse(final String startdatokontraktansettelse) {
        this.startdatokontraktansettelse = startdatokontraktansettelse;
    }

    @java.lang.SuppressWarnings("all")
    public void setBegrunnelse(final String begrunnelse) {
        this.begrunnelse = begrunnelse;
    }

    @java.lang.SuppressWarnings("all")
    public void setA1grunnlag(final String a1grunnlag) {
        this.a1grunnlag = a1grunnlag;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Unntak)) return false;
        final Unntak other = (Unntak) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$startdatoansattforsikret = this.getStartdatoansattforsikret();
        final java.lang.Object other$startdatoansattforsikret = other.getStartdatoansattforsikret();
        if (this$startdatoansattforsikret == null ? other$startdatoansattforsikret != null : !this$startdatoansattforsikret.equals(other$startdatoansattforsikret))
            return false;
        final java.lang.Object this$grunnlag = this.getGrunnlag();
        final java.lang.Object other$grunnlag = other.getGrunnlag();
        if (this$grunnlag == null ? other$grunnlag != null : !this$grunnlag.equals(other$grunnlag)) return false;
        final java.lang.Object this$spesielleomstendigheter = this.getSpesielleomstendigheter();
        final java.lang.Object other$spesielleomstendigheter = other.getSpesielleomstendigheter();
        if (this$spesielleomstendigheter == null ? other$spesielleomstendigheter != null : !this$spesielleomstendigheter.equals(other$spesielleomstendigheter))
            return false;
        final java.lang.Object this$startdatokontraktansettelse = this.getStartdatokontraktansettelse();
        final java.lang.Object other$startdatokontraktansettelse = other.getStartdatokontraktansettelse();
        if (this$startdatokontraktansettelse == null ? other$startdatokontraktansettelse != null : !this$startdatokontraktansettelse.equals(other$startdatokontraktansettelse))
            return false;
        final java.lang.Object this$begrunnelse = this.getBegrunnelse();
        final java.lang.Object other$begrunnelse = other.getBegrunnelse();
        if (this$begrunnelse == null ? other$begrunnelse != null : !this$begrunnelse.equals(other$begrunnelse))
            return false;
        final java.lang.Object this$a1grunnlag = this.getA1grunnlag();
        final java.lang.Object other$a1grunnlag = other.getA1grunnlag();
        if (this$a1grunnlag == null ? other$a1grunnlag != null : !this$a1grunnlag.equals(other$a1grunnlag))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Unntak;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $startdatoansattforsikret = this.getStartdatoansattforsikret();
        result = result * PRIME + ($startdatoansattforsikret == null ? 43 : $startdatoansattforsikret.hashCode());
        final java.lang.Object $grunnlag = this.getGrunnlag();
        result = result * PRIME + ($grunnlag == null ? 43 : $grunnlag.hashCode());
        final java.lang.Object $spesielleomstendigheter = this.getSpesielleomstendigheter();
        result = result * PRIME + ($spesielleomstendigheter == null ? 43 : $spesielleomstendigheter.hashCode());
        final java.lang.Object $startdatokontraktansettelse = this.getStartdatokontraktansettelse();
        result = result * PRIME + ($startdatokontraktansettelse == null ? 43 : $startdatokontraktansettelse.hashCode());
        final java.lang.Object $begrunnelse = this.getBegrunnelse();
        result = result * PRIME + ($begrunnelse == null ? 43 : $begrunnelse.hashCode());
        final java.lang.Object $a1grunnlag = this.getA1grunnlag();
        result = result * PRIME + ($a1grunnlag == null ? 43 : $a1grunnlag.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Unntak(startdatoansattforsikret=" + this.getStartdatoansattforsikret() + ", grunnlag=" + this.getGrunnlag() + ", spesielleomstendigheter=" + this.getSpesielleomstendigheter() + ", startdatokontraktansettelse=" + this.getStartdatokontraktansettelse() + ", begrunnelse=" + this.getBegrunnelse() + ", a1grunnlag=" + this.getA1grunnlag() + ")";
    }
}
