// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.nav;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class X006FjernInstitusjon {
    private Institusjon institusjon;

    @java.lang.SuppressWarnings("all")
    public X006FjernInstitusjon() {
    }

    @java.lang.SuppressWarnings("all")
    public Institusjon getInstitusjon() {
        return this.institusjon;
    }

    @java.lang.SuppressWarnings("all")
    public void setInstitusjon(final Institusjon institusjon) {
        this.institusjon = institusjon;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof X006FjernInstitusjon)) return false;
        final X006FjernInstitusjon other = (X006FjernInstitusjon) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$institusjon = this.getInstitusjon();
        final java.lang.Object other$institusjon = other.getInstitusjon();
        if (this$institusjon == null ? other$institusjon != null : !this$institusjon.equals(other$institusjon))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof X006FjernInstitusjon;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $institusjon = this.getInstitusjon();
        result = result * PRIME + ($institusjon == null ? 43 : $institusjon.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "X006FjernInstitusjon(institusjon=" + this.getInstitusjon() + ")";
    }
}
