// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.web.identrekvisisjon.dto;

public class IdentRekvisisjonDokumentasjon {
    private String dokumentasjonstype;
    private String ident;

    @java.lang.SuppressWarnings("all")
    public String getDokumentasjonstype() {
        return this.dokumentasjonstype;
    }

    @java.lang.SuppressWarnings("all")
    public String getIdent() {
        return this.ident;
    }

    @java.lang.SuppressWarnings("all")
    public void setDokumentasjonstype(final String dokumentasjonstype) {
        this.dokumentasjonstype = dokumentasjonstype;
    }

    @java.lang.SuppressWarnings("all")
    public void setIdent(final String ident) {
        this.ident = ident;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof IdentRekvisisjonDokumentasjon)) return false;
        final IdentRekvisisjonDokumentasjon other = (IdentRekvisisjonDokumentasjon) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$dokumentasjonstype = this.getDokumentasjonstype();
        final java.lang.Object other$dokumentasjonstype = other.getDokumentasjonstype();
        if (this$dokumentasjonstype == null ? other$dokumentasjonstype != null : !this$dokumentasjonstype.equals(other$dokumentasjonstype))
            return false;
        final java.lang.Object this$ident = this.getIdent();
        final java.lang.Object other$ident = other.getIdent();
        if (this$ident == null ? other$ident != null : !this$ident.equals(other$ident)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof IdentRekvisisjonDokumentasjon;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $dokumentasjonstype = this.getDokumentasjonstype();
        result = result * PRIME + ($dokumentasjonstype == null ? 43 : $dokumentasjonstype.hashCode());
        final java.lang.Object $ident = this.getIdent();
        result = result * PRIME + ($ident == null ? 43 : $ident.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "IdentRekvisisjonDokumentasjon(dokumentasjonstype=" + this.getDokumentasjonstype() + ", ident=" + this.getIdent() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public IdentRekvisisjonDokumentasjon() {
    }

    @java.lang.SuppressWarnings("all")
    public IdentRekvisisjonDokumentasjon(final String dokumentasjonstype, final String ident) {
        this.dokumentasjonstype = dokumentasjonstype;
        this.ident = ident;
    }
}
