// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.web.identrekvisisjon.dto;

import lombok.*;

public class IdentRekvisisjonKilde {
    private String institusjon;
    private String landkode;


    @java.lang.SuppressWarnings("all")
    public static class IdentRekvisisjonKildeBuilder {
        @java.lang.SuppressWarnings("all")
        private String institusjon;
        @java.lang.SuppressWarnings("all")
        private String landkode;

        @java.lang.SuppressWarnings("all")
        IdentRekvisisjonKildeBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonKilde.IdentRekvisisjonKildeBuilder institusjon(final String institusjon) {
            this.institusjon = institusjon;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonKilde.IdentRekvisisjonKildeBuilder landkode(final String landkode) {
            this.landkode = landkode;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonKilde build() {
            return new IdentRekvisisjonKilde(this.institusjon, this.landkode);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "IdentRekvisisjonKilde.IdentRekvisisjonKildeBuilder(institusjon=" + this.institusjon + ", landkode=" + this.landkode + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static IdentRekvisisjonKilde.IdentRekvisisjonKildeBuilder builder() {
        return new IdentRekvisisjonKilde.IdentRekvisisjonKildeBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getInstitusjon() {
        return this.institusjon;
    }

    @java.lang.SuppressWarnings("all")
    public String getLandkode() {
        return this.landkode;
    }

    @java.lang.SuppressWarnings("all")
    public void setInstitusjon(final String institusjon) {
        this.institusjon = institusjon;
    }

    @java.lang.SuppressWarnings("all")
    public void setLandkode(final String landkode) {
        this.landkode = landkode;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof IdentRekvisisjonKilde)) return false;
        final IdentRekvisisjonKilde other = (IdentRekvisisjonKilde) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$institusjon = this.getInstitusjon();
        final java.lang.Object other$institusjon = other.getInstitusjon();
        if (this$institusjon == null ? other$institusjon != null : !this$institusjon.equals(other$institusjon)) return false;
        final java.lang.Object this$landkode = this.getLandkode();
        final java.lang.Object other$landkode = other.getLandkode();
        if (this$landkode == null ? other$landkode != null : !this$landkode.equals(other$landkode)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof IdentRekvisisjonKilde;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $institusjon = this.getInstitusjon();
        result = result * PRIME + ($institusjon == null ? 43 : $institusjon.hashCode());
        final java.lang.Object $landkode = this.getLandkode();
        result = result * PRIME + ($landkode == null ? 43 : $landkode.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "IdentRekvisisjonKilde(institusjon=" + this.getInstitusjon() + ", landkode=" + this.getLandkode() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public IdentRekvisisjonKilde() {
    }

    @java.lang.SuppressWarnings("all")
    public IdentRekvisisjonKilde(final String institusjon, final String landkode) {
        this.institusjon = institusjon;
        this.landkode = landkode;
    }
}
