// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.web.identrekvisisjon.dto;

import lombok.*;

public class IdentRekvisisjonRelasjon {
    private String minRolleForPerson;
    private String relatertPersonsRolle;
    private String relatertPersonsIdent;


    @java.lang.SuppressWarnings("all")
    public static class IdentRekvisisjonRelasjonBuilder {
        @java.lang.SuppressWarnings("all")
        private String minRolleForPerson;
        @java.lang.SuppressWarnings("all")
        private String relatertPersonsRolle;
        @java.lang.SuppressWarnings("all")
        private String relatertPersonsIdent;

        @java.lang.SuppressWarnings("all")
        IdentRekvisisjonRelasjonBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonRelasjon.IdentRekvisisjonRelasjonBuilder minRolleForPerson(final String minRolleForPerson) {
            this.minRolleForPerson = minRolleForPerson;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonRelasjon.IdentRekvisisjonRelasjonBuilder relatertPersonsRolle(final String relatertPersonsRolle) {
            this.relatertPersonsRolle = relatertPersonsRolle;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonRelasjon.IdentRekvisisjonRelasjonBuilder relatertPersonsIdent(final String relatertPersonsIdent) {
            this.relatertPersonsIdent = relatertPersonsIdent;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonRelasjon build() {
            return new IdentRekvisisjonRelasjon(this.minRolleForPerson, this.relatertPersonsRolle, this.relatertPersonsIdent);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "IdentRekvisisjonRelasjon.IdentRekvisisjonRelasjonBuilder(minRolleForPerson=" + this.minRolleForPerson + ", relatertPersonsRolle=" + this.relatertPersonsRolle + ", relatertPersonsIdent=" + this.relatertPersonsIdent + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static IdentRekvisisjonRelasjon.IdentRekvisisjonRelasjonBuilder builder() {
        return new IdentRekvisisjonRelasjon.IdentRekvisisjonRelasjonBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getMinRolleForPerson() {
        return this.minRolleForPerson;
    }

    @java.lang.SuppressWarnings("all")
    public String getRelatertPersonsRolle() {
        return this.relatertPersonsRolle;
    }

    @java.lang.SuppressWarnings("all")
    public String getRelatertPersonsIdent() {
        return this.relatertPersonsIdent;
    }

    @java.lang.SuppressWarnings("all")
    public void setMinRolleForPerson(final String minRolleForPerson) {
        this.minRolleForPerson = minRolleForPerson;
    }

    @java.lang.SuppressWarnings("all")
    public void setRelatertPersonsRolle(final String relatertPersonsRolle) {
        this.relatertPersonsRolle = relatertPersonsRolle;
    }

    @java.lang.SuppressWarnings("all")
    public void setRelatertPersonsIdent(final String relatertPersonsIdent) {
        this.relatertPersonsIdent = relatertPersonsIdent;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof IdentRekvisisjonRelasjon)) return false;
        final IdentRekvisisjonRelasjon other = (IdentRekvisisjonRelasjon) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$minRolleForPerson = this.getMinRolleForPerson();
        final java.lang.Object other$minRolleForPerson = other.getMinRolleForPerson();
        if (this$minRolleForPerson == null ? other$minRolleForPerson != null : !this$minRolleForPerson.equals(other$minRolleForPerson)) return false;
        final java.lang.Object this$relatertPersonsRolle = this.getRelatertPersonsRolle();
        final java.lang.Object other$relatertPersonsRolle = other.getRelatertPersonsRolle();
        if (this$relatertPersonsRolle == null ? other$relatertPersonsRolle != null : !this$relatertPersonsRolle.equals(other$relatertPersonsRolle)) return false;
        final java.lang.Object this$relatertPersonsIdent = this.getRelatertPersonsIdent();
        final java.lang.Object other$relatertPersonsIdent = other.getRelatertPersonsIdent();
        if (this$relatertPersonsIdent == null ? other$relatertPersonsIdent != null : !this$relatertPersonsIdent.equals(other$relatertPersonsIdent)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof IdentRekvisisjonRelasjon;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $minRolleForPerson = this.getMinRolleForPerson();
        result = result * PRIME + ($minRolleForPerson == null ? 43 : $minRolleForPerson.hashCode());
        final java.lang.Object $relatertPersonsRolle = this.getRelatertPersonsRolle();
        result = result * PRIME + ($relatertPersonsRolle == null ? 43 : $relatertPersonsRolle.hashCode());
        final java.lang.Object $relatertPersonsIdent = this.getRelatertPersonsIdent();
        result = result * PRIME + ($relatertPersonsIdent == null ? 43 : $relatertPersonsIdent.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "IdentRekvisisjonRelasjon(minRolleForPerson=" + this.getMinRolleForPerson() + ", relatertPersonsRolle=" + this.getRelatertPersonsRolle() + ", relatertPersonsIdent=" + this.getRelatertPersonsIdent() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public IdentRekvisisjonRelasjon() {
    }

    @java.lang.SuppressWarnings("all")
    public IdentRekvisisjonRelasjon(final String minRolleForPerson, final String relatertPersonsRolle, final String relatertPersonsIdent) {
        this.minRolleForPerson = minRolleForPerson;
        this.relatertPersonsRolle = relatertPersonsRolle;
        this.relatertPersonsIdent = relatertPersonsIdent;
    }
}
