// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.web.identrekvisisjon.dto;

import no.nav.melosys.eessi.integration.pdl.web.identrekvisisjon.dto.adresse.Vegadresse;

public class IdentRekvisisjonNorskVegadresse extends Vegadresse {
    private String adressenavn;
    private String husnummer;
    private String husbokstav;
    private String postnummer;
    private String bruksenhetsnummer;
    private String tilleggsnavn;
    private String matrikkelId;


    @java.lang.SuppressWarnings("all")
    public static class IdentRekvisisjonNorskVegadresseBuilder {
        @java.lang.SuppressWarnings("all")
        private String adressenavn;
        @java.lang.SuppressWarnings("all")
        private String husnummer;
        @java.lang.SuppressWarnings("all")
        private String husbokstav;
        @java.lang.SuppressWarnings("all")
        private String postnummer;
        @java.lang.SuppressWarnings("all")
        private String bruksenhetsnummer;
        @java.lang.SuppressWarnings("all")
        private String tilleggsnavn;
        @java.lang.SuppressWarnings("all")
        private String matrikkelId;

        @java.lang.SuppressWarnings("all")
        IdentRekvisisjonNorskVegadresseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonNorskVegadresse.IdentRekvisisjonNorskVegadresseBuilder adressenavn(final String adressenavn) {
            this.adressenavn = adressenavn;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonNorskVegadresse.IdentRekvisisjonNorskVegadresseBuilder husnummer(final String husnummer) {
            this.husnummer = husnummer;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonNorskVegadresse.IdentRekvisisjonNorskVegadresseBuilder husbokstav(final String husbokstav) {
            this.husbokstav = husbokstav;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonNorskVegadresse.IdentRekvisisjonNorskVegadresseBuilder postnummer(final String postnummer) {
            this.postnummer = postnummer;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonNorskVegadresse.IdentRekvisisjonNorskVegadresseBuilder bruksenhetsnummer(final String bruksenhetsnummer) {
            this.bruksenhetsnummer = bruksenhetsnummer;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonNorskVegadresse.IdentRekvisisjonNorskVegadresseBuilder tilleggsnavn(final String tilleggsnavn) {
            this.tilleggsnavn = tilleggsnavn;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonNorskVegadresse.IdentRekvisisjonNorskVegadresseBuilder matrikkelId(final String matrikkelId) {
            this.matrikkelId = matrikkelId;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public IdentRekvisisjonNorskVegadresse build() {
            return new IdentRekvisisjonNorskVegadresse(this.adressenavn, this.husnummer, this.husbokstav, this.postnummer, this.bruksenhetsnummer, this.tilleggsnavn, this.matrikkelId);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "IdentRekvisisjonNorskVegadresse.IdentRekvisisjonNorskVegadresseBuilder(adressenavn=" + this.adressenavn + ", husnummer=" + this.husnummer + ", husbokstav=" + this.husbokstav + ", postnummer=" + this.postnummer + ", bruksenhetsnummer=" + this.bruksenhetsnummer + ", tilleggsnavn=" + this.tilleggsnavn + ", matrikkelId=" + this.matrikkelId + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static IdentRekvisisjonNorskVegadresse.IdentRekvisisjonNorskVegadresseBuilder builder() {
        return new IdentRekvisisjonNorskVegadresse.IdentRekvisisjonNorskVegadresseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getAdressenavn() {
        return this.adressenavn;
    }

    @java.lang.SuppressWarnings("all")
    public String getHusnummer() {
        return this.husnummer;
    }

    @java.lang.SuppressWarnings("all")
    public String getHusbokstav() {
        return this.husbokstav;
    }

    @java.lang.SuppressWarnings("all")
    public String getPostnummer() {
        return this.postnummer;
    }

    @java.lang.SuppressWarnings("all")
    public String getBruksenhetsnummer() {
        return this.bruksenhetsnummer;
    }

    @java.lang.SuppressWarnings("all")
    public String getTilleggsnavn() {
        return this.tilleggsnavn;
    }

    @java.lang.SuppressWarnings("all")
    public String getMatrikkelId() {
        return this.matrikkelId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAdressenavn(final String adressenavn) {
        this.adressenavn = adressenavn;
    }

    @java.lang.SuppressWarnings("all")
    public void setHusnummer(final String husnummer) {
        this.husnummer = husnummer;
    }

    @java.lang.SuppressWarnings("all")
    public void setHusbokstav(final String husbokstav) {
        this.husbokstav = husbokstav;
    }

    @java.lang.SuppressWarnings("all")
    public void setPostnummer(final String postnummer) {
        this.postnummer = postnummer;
    }

    @java.lang.SuppressWarnings("all")
    public void setBruksenhetsnummer(final String bruksenhetsnummer) {
        this.bruksenhetsnummer = bruksenhetsnummer;
    }

    @java.lang.SuppressWarnings("all")
    public void setTilleggsnavn(final String tilleggsnavn) {
        this.tilleggsnavn = tilleggsnavn;
    }

    @java.lang.SuppressWarnings("all")
    public void setMatrikkelId(final String matrikkelId) {
        this.matrikkelId = matrikkelId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "IdentRekvisisjonNorskVegadresse(adressenavn=" + this.getAdressenavn() + ", husnummer=" + this.getHusnummer() + ", husbokstav=" + this.getHusbokstav() + ", postnummer=" + this.getPostnummer() + ", bruksenhetsnummer=" + this.getBruksenhetsnummer() + ", tilleggsnavn=" + this.getTilleggsnavn() + ", matrikkelId=" + this.getMatrikkelId() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public IdentRekvisisjonNorskVegadresse(final String adressenavn, final String husnummer, final String husbokstav, final String postnummer, final String bruksenhetsnummer, final String tilleggsnavn, final String matrikkelId) {
        this.adressenavn = adressenavn;
        this.husnummer = husnummer;
        this.husbokstav = husbokstav;
        this.postnummer = postnummer;
        this.bruksenhetsnummer = bruksenhetsnummer;
        this.tilleggsnavn = tilleggsnavn;
        this.matrikkelId = matrikkelId;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof IdentRekvisisjonNorskVegadresse)) return false;
        final IdentRekvisisjonNorskVegadresse other = (IdentRekvisisjonNorskVegadresse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$adressenavn = this.getAdressenavn();
        final java.lang.Object other$adressenavn = other.getAdressenavn();
        if (this$adressenavn == null ? other$adressenavn != null : !this$adressenavn.equals(other$adressenavn))
            return false;
        final java.lang.Object this$husnummer = this.getHusnummer();
        final java.lang.Object other$husnummer = other.getHusnummer();
        if (this$husnummer == null ? other$husnummer != null : !this$husnummer.equals(other$husnummer)) return false;
        final java.lang.Object this$husbokstav = this.getHusbokstav();
        final java.lang.Object other$husbokstav = other.getHusbokstav();
        if (this$husbokstav == null ? other$husbokstav != null : !this$husbokstav.equals(other$husbokstav))
            return false;
        final java.lang.Object this$postnummer = this.getPostnummer();
        final java.lang.Object other$postnummer = other.getPostnummer();
        if (this$postnummer == null ? other$postnummer != null : !this$postnummer.equals(other$postnummer))
            return false;
        final java.lang.Object this$bruksenhetsnummer = this.getBruksenhetsnummer();
        final java.lang.Object other$bruksenhetsnummer = other.getBruksenhetsnummer();
        if (this$bruksenhetsnummer == null ? other$bruksenhetsnummer != null : !this$bruksenhetsnummer.equals(other$bruksenhetsnummer))
            return false;
        final java.lang.Object this$tilleggsnavn = this.getTilleggsnavn();
        final java.lang.Object other$tilleggsnavn = other.getTilleggsnavn();
        if (this$tilleggsnavn == null ? other$tilleggsnavn != null : !this$tilleggsnavn.equals(other$tilleggsnavn))
            return false;
        final java.lang.Object this$matrikkelId = this.getMatrikkelId();
        final java.lang.Object other$matrikkelId = other.getMatrikkelId();
        if (this$matrikkelId == null ? other$matrikkelId != null : !this$matrikkelId.equals(other$matrikkelId))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof IdentRekvisisjonNorskVegadresse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $adressenavn = this.getAdressenavn();
        result = result * PRIME + ($adressenavn == null ? 43 : $adressenavn.hashCode());
        final java.lang.Object $husnummer = this.getHusnummer();
        result = result * PRIME + ($husnummer == null ? 43 : $husnummer.hashCode());
        final java.lang.Object $husbokstav = this.getHusbokstav();
        result = result * PRIME + ($husbokstav == null ? 43 : $husbokstav.hashCode());
        final java.lang.Object $postnummer = this.getPostnummer();
        result = result * PRIME + ($postnummer == null ? 43 : $postnummer.hashCode());
        final java.lang.Object $bruksenhetsnummer = this.getBruksenhetsnummer();
        result = result * PRIME + ($bruksenhetsnummer == null ? 43 : $bruksenhetsnummer.hashCode());
        final java.lang.Object $tilleggsnavn = this.getTilleggsnavn();
        result = result * PRIME + ($tilleggsnavn == null ? 43 : $tilleggsnavn.hashCode());
        final java.lang.Object $matrikkelId = this.getMatrikkelId();
        result = result * PRIME + ($matrikkelId == null ? 43 : $matrikkelId.hashCode());
        return result;
    }
}
