server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: melosys-eessi

melosys:
  systemuser:
    username: ${SRV_USERNAME}
    password: ${SRV_PASSWORD}
  integrations:
    euxapp-url: ${EUXAPP_URL}
    reststs-url: ${RESTSTS_URL}
    sts-url: ${STS_URL}
    dokarkivsed-url: ${DOKARKIVSED_URL}
    aktoer-url: ${AKTOER_URL}
    dokkat:
      typeid-url: ${DOKKATTYPEID_URL}
      typeinfo-url: ${DOKKATTYPEINFO_URL}
    gsak:
      sak-url: ${SAK_URL}
  api:
    security:
      header-name: ${API_KEY_HEADER}
      header-value: ${API_KEY_VALUE}
