server:
  port: 8081
  servlet:
    context-path: /api

spring:
  application:
    name: melosys-eessi

melosys:
  systemuser:
    username: ${SRV_USERNAME}
    password: ${SRV_PASSWORD}
  integrations:
    euxapp-url: ${EUXAPP_URL}
    reststs-url: ${RESTSTS_URL}
  api:
    security:
      header-name: ${API_KEY_HEADER}
      header-value: ${API_KEY_VALUE}
