server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: melosys-eessi
  datasource:
    url: jdbc:postgresql://${PG_HOST}:5432/${DATABASE_NAME}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true #fix for jdbc bug i postgres-driver som krasjer app
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      schema.registry.url: ${KAFKA_SCHEMA_REGISTRY_URL}
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${melosys.systemuser.username}" password="${melosys.systemuser.password}";
      reconnect.backoff.ms: 1000

melosys:
  systemuser:
    username: ${SRV_USERNAME}
    password: ${SRV_PASSWORD}
  integrations:
    euxapp-url: ${EUXAPP_URL}
    reststs-url: ${RESTSTS_URL}
    sts-url: ${STS_URL}
    dokarkivsed-url: ${DOKARKIVSED_URL}
    dokmotinngaaende-url: ${DOKMOTINNGAAENDE_URL}
    aktoer-url: ${AKTOER_URL}
    dokkat:
      typeid-url: ${DOKKATTYPEID_URL}
      typeinfo-url: ${DOKKATTYPEINFO_URL}
    gsak:
      sak-url: ${SAK_URL}
  api:
    security:
      header-name: ${API_KEY_HEADER}
      header-value: ${API_KEY_VALUE}
