// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.buc;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class Action {
    private String name;
    private String documentType;
    private String documentId;
    private String operation;

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public String getDocumentType() {
        return this.documentType;
    }

    @java.lang.SuppressWarnings("all")
    public String getDocumentId() {
        return this.documentId;
    }

    @java.lang.SuppressWarnings("all")
    public String getOperation() {
        return this.operation;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.SuppressWarnings("all")
    public void setDocumentType(final String documentType) {
        this.documentType = documentType;
    }

    @java.lang.SuppressWarnings("all")
    public void setDocumentId(final String documentId) {
        this.documentId = documentId;
    }

    @java.lang.SuppressWarnings("all")
    public void setOperation(final String operation) {
        this.operation = operation;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Action)) return false;
        final Action other = (Action) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        final java.lang.Object this$documentType = this.getDocumentType();
        final java.lang.Object other$documentType = other.getDocumentType();
        if (this$documentType == null ? other$documentType != null : !this$documentType.equals(other$documentType)) return false;
        final java.lang.Object this$documentId = this.getDocumentId();
        final java.lang.Object other$documentId = other.getDocumentId();
        if (this$documentId == null ? other$documentId != null : !this$documentId.equals(other$documentId)) return false;
        final java.lang.Object this$operation = this.getOperation();
        final java.lang.Object other$operation = other.getOperation();
        if (this$operation == null ? other$operation != null : !this$operation.equals(other$operation)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Action;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        final java.lang.Object $documentType = this.getDocumentType();
        result = result * PRIME + ($documentType == null ? 43 : $documentType.hashCode());
        final java.lang.Object $documentId = this.getDocumentId();
        result = result * PRIME + ($documentId == null ? 43 : $documentId.hashCode());
        final java.lang.Object $operation = this.getOperation();
        result = result * PRIME + ($operation == null ? 43 : $operation.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Action(name=" + this.getName() + ", documentType=" + this.getDocumentType() + ", documentId=" + this.getDocumentId() + ", operation=" + this.getOperation() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Action() {
    }

    @java.lang.SuppressWarnings("all")
    public Action(final String name, final String documentType, final String documentId, final String operation) {
        this.name = name;
        this.documentType = documentType;
        this.documentId = documentId;
        this.operation = operation;
    }
}
