// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.service.personsok;

import java.time.LocalDate;
import java.util.Collection;

public class PersonsokKriterier {
    private String fornavn;
    private String etternavn;
    private LocalDate foedselsdato;
    private Collection<String> statsborgerskapISO2;

    @java.lang.SuppressWarnings("all")
    PersonsokKriterier(final String fornavn, final String etternavn, final LocalDate foedselsdato, final Collection<String> statsborgerskapISO2) {
        this.fornavn = fornavn;
        this.etternavn = etternavn;
        this.foedselsdato = foedselsdato;
        this.statsborgerskapISO2 = statsborgerskapISO2;
    }


    @java.lang.SuppressWarnings("all")
    public static class PersonsokKriterierBuilder {
        @java.lang.SuppressWarnings("all")
        private String fornavn;
        @java.lang.SuppressWarnings("all")
        private String etternavn;
        @java.lang.SuppressWarnings("all")
        private LocalDate foedselsdato;
        @java.lang.SuppressWarnings("all")
        private Collection<String> statsborgerskapISO2;

        @java.lang.SuppressWarnings("all")
        PersonsokKriterierBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PersonsokKriterier.PersonsokKriterierBuilder fornavn(final String fornavn) {
            this.fornavn = fornavn;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PersonsokKriterier.PersonsokKriterierBuilder etternavn(final String etternavn) {
            this.etternavn = etternavn;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PersonsokKriterier.PersonsokKriterierBuilder foedselsdato(final LocalDate foedselsdato) {
            this.foedselsdato = foedselsdato;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PersonsokKriterier.PersonsokKriterierBuilder statsborgerskapISO2(final Collection<String> statsborgerskapISO2) {
            this.statsborgerskapISO2 = statsborgerskapISO2;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public PersonsokKriterier build() {
            return new PersonsokKriterier(this.fornavn, this.etternavn, this.foedselsdato, this.statsborgerskapISO2);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "PersonsokKriterier.PersonsokKriterierBuilder(fornavn=" + this.fornavn + ", etternavn=" + this.etternavn + ", foedselsdato=" + this.foedselsdato + ", statsborgerskapISO2=" + this.statsborgerskapISO2 + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static PersonsokKriterier.PersonsokKriterierBuilder builder() {
        return new PersonsokKriterier.PersonsokKriterierBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getFornavn() {
        return this.fornavn;
    }

    @java.lang.SuppressWarnings("all")
    public String getEtternavn() {
        return this.etternavn;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getFoedselsdato() {
        return this.foedselsdato;
    }

    @java.lang.SuppressWarnings("all")
    public Collection<String> getStatsborgerskapISO2() {
        return this.statsborgerskapISO2;
    }

    @java.lang.SuppressWarnings("all")
    public void setFornavn(final String fornavn) {
        this.fornavn = fornavn;
    }

    @java.lang.SuppressWarnings("all")
    public void setEtternavn(final String etternavn) {
        this.etternavn = etternavn;
    }

    @java.lang.SuppressWarnings("all")
    public void setFoedselsdato(final LocalDate foedselsdato) {
        this.foedselsdato = foedselsdato;
    }

    @java.lang.SuppressWarnings("all")
    public void setStatsborgerskapISO2(final Collection<String> statsborgerskapISO2) {
        this.statsborgerskapISO2 = statsborgerskapISO2;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PersonsokKriterier)) return false;
        final PersonsokKriterier other = (PersonsokKriterier) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$fornavn = this.getFornavn();
        final java.lang.Object other$fornavn = other.getFornavn();
        if (this$fornavn == null ? other$fornavn != null : !this$fornavn.equals(other$fornavn)) return false;
        final java.lang.Object this$etternavn = this.getEtternavn();
        final java.lang.Object other$etternavn = other.getEtternavn();
        if (this$etternavn == null ? other$etternavn != null : !this$etternavn.equals(other$etternavn)) return false;
        final java.lang.Object this$foedselsdato = this.getFoedselsdato();
        final java.lang.Object other$foedselsdato = other.getFoedselsdato();
        if (this$foedselsdato == null ? other$foedselsdato != null : !this$foedselsdato.equals(other$foedselsdato))
            return false;
        final java.lang.Object this$statsborgerskapISO2 = this.getStatsborgerskapISO2();
        final java.lang.Object other$statsborgerskapISO2 = other.getStatsborgerskapISO2();
        if (this$statsborgerskapISO2 == null ? other$statsborgerskapISO2 != null : !this$statsborgerskapISO2.equals(other$statsborgerskapISO2))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PersonsokKriterier;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $fornavn = this.getFornavn();
        result = result * PRIME + ($fornavn == null ? 43 : $fornavn.hashCode());
        final java.lang.Object $etternavn = this.getEtternavn();
        result = result * PRIME + ($etternavn == null ? 43 : $etternavn.hashCode());
        final java.lang.Object $foedselsdato = this.getFoedselsdato();
        result = result * PRIME + ($foedselsdato == null ? 43 : $foedselsdato.hashCode());
        final java.lang.Object $statsborgerskapISO2 = this.getStatsborgerskapISO2();
        result = result * PRIME + ($statsborgerskapISO2 == null ? 43 : $statsborgerskapISO2.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PersonsokKriterier(fornavn=" + this.getFornavn() + ", etternavn=" + this.getEtternavn() + ", foedselsdato=" + this.getFoedselsdato() + ", statsborgerskapISO2=" + this.getStatsborgerskapISO2() + ")";
    }
}
