// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.service.personsok;

public class PersonSokResponse {
    private String ident;

    @java.lang.SuppressWarnings("all")
    public String getIdent() {
        return this.ident;
    }

    @java.lang.SuppressWarnings("all")
    public void setIdent(final String ident) {
        this.ident = ident;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PersonSokResponse)) return false;
        final PersonSokResponse other = (PersonSokResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$ident = this.getIdent();
        final java.lang.Object other$ident = other.getIdent();
        if (this$ident == null ? other$ident != null : !this$ident.equals(other$ident)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PersonSokResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $ident = this.getIdent();
        result = result * PRIME + ($ident == null ? 43 : $ident.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PersonSokResponse(ident=" + this.getIdent() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public PersonSokResponse(final String ident) {
        this.ident = ident;
    }

    @java.lang.SuppressWarnings("all")
    public PersonSokResponse() {
    }
}
