apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: melosys-eessi
  namespace: t8
  labels:
    team: teammelosys
spec:
  image: {{image}}:{{tag}}
  port: 8080
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 50
  liveness:
    path: /api/internal/health
    initialDelay: 60
    timeout: 10
  readiness:
    path: /api/internal/health
    initialDelay: 60
    timeout: 10
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      cpu: 500m
      memory: 512Mi
  vault:
    enabled: true
  prometheus:
    enabled: true
    path: /api/internal/prometheus
  ingresses:
    - "https://melosys-eessi-t8.nais.preprod.local"
  env:
    - name: spring.profiles.active
      value: nais