apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: melosys-eessi
  namespace: {{NAMESPACE}}
  labels:
    team: teammelosys
spec:
  image: {{image}}
  port: 8080
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  liveness:
    path: /internal/health
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/health
    initialDelay: 60
    timeout: 10
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 200m
      memory: 512Mi
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/serviceuser
        kvPath: /serviceuser/data/{{VAULT_CLUSTER}}/srvmelosys-eessi
  prometheus:
    enabled: true
    path: /internal/prometheus
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: nais
