// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.person;

import java.time.LocalDate;
import java.util.Collection;

public final class PersonModell {
    private final String ident;
    private final String fornavn;
    private final String etternavn;
    private final LocalDate fødselsdato;
    private final Collection<String> statsborgerskapLandkodeISO2;
    private final Collection<UtenlandskId> utenlandskId;
    private final boolean erOpphørt;
    private final Kjønn kjønn;

    @java.lang.SuppressWarnings("all")
    PersonModell(final String ident, final String fornavn, final String etternavn, final LocalDate fødselsdato, final Collection<String> statsborgerskapLandkodeISO2, final Collection<UtenlandskId> utenlandskId, final boolean erOpphørt, final Kjønn kjønn) {
        this.ident = ident;
        this.fornavn = fornavn;
        this.etternavn = etternavn;
        this.fødselsdato = fødselsdato;
        this.statsborgerskapLandkodeISO2 = statsborgerskapLandkodeISO2;
        this.utenlandskId = utenlandskId;
        this.erOpphørt = erOpphørt;
        this.kjønn = kjønn;
    }


    @java.lang.SuppressWarnings("all")
    public static class PersonModellBuilder {
        @java.lang.SuppressWarnings("all")
        private String ident;
        @java.lang.SuppressWarnings("all")
        private String fornavn;
        @java.lang.SuppressWarnings("all")
        private String etternavn;
        @java.lang.SuppressWarnings("all")
        private LocalDate fødselsdato;
        @java.lang.SuppressWarnings("all")
        private Collection<String> statsborgerskapLandkodeISO2;
        @java.lang.SuppressWarnings("all")
        private Collection<UtenlandskId> utenlandskId;
        @java.lang.SuppressWarnings("all")
        private boolean erOpphørt;
        @java.lang.SuppressWarnings("all")
        private Kjønn kjønn;

        @java.lang.SuppressWarnings("all")
        PersonModellBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PersonModell.PersonModellBuilder ident(final String ident) {
            this.ident = ident;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PersonModell.PersonModellBuilder fornavn(final String fornavn) {
            this.fornavn = fornavn;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PersonModell.PersonModellBuilder etternavn(final String etternavn) {
            this.etternavn = etternavn;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PersonModell.PersonModellBuilder fødselsdato(final LocalDate fødselsdato) {
            this.fødselsdato = fødselsdato;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PersonModell.PersonModellBuilder statsborgerskapLandkodeISO2(final Collection<String> statsborgerskapLandkodeISO2) {
            this.statsborgerskapLandkodeISO2 = statsborgerskapLandkodeISO2;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PersonModell.PersonModellBuilder utenlandskId(final Collection<UtenlandskId> utenlandskId) {
            this.utenlandskId = utenlandskId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PersonModell.PersonModellBuilder erOpphørt(final boolean erOpphørt) {
            this.erOpphørt = erOpphørt;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public PersonModell.PersonModellBuilder kjønn(final Kjønn kjønn) {
            this.kjønn = kjønn;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public PersonModell build() {
            return new PersonModell(this.ident, this.fornavn, this.etternavn, this.fødselsdato, this.statsborgerskapLandkodeISO2, this.utenlandskId, this.erOpphørt, this.kjønn);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "PersonModell.PersonModellBuilder(ident=" + this.ident + ", fornavn=" + this.fornavn + ", etternavn=" + this.etternavn + ", fødselsdato=" + this.fødselsdato + ", statsborgerskapLandkodeISO2=" + this.statsborgerskapLandkodeISO2 + ", utenlandskId=" + this.utenlandskId + ", erOpphørt=" + this.erOpphørt + ", kjønn=" + this.kjønn + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static PersonModell.PersonModellBuilder builder() {
        return new PersonModell.PersonModellBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getIdent() {
        return this.ident;
    }

    @java.lang.SuppressWarnings("all")
    public String getFornavn() {
        return this.fornavn;
    }

    @java.lang.SuppressWarnings("all")
    public String getEtternavn() {
        return this.etternavn;
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getFødselsdato() {
        return this.fødselsdato;
    }

    @java.lang.SuppressWarnings("all")
    public Collection<String> getStatsborgerskapLandkodeISO2() {
        return this.statsborgerskapLandkodeISO2;
    }

    @java.lang.SuppressWarnings("all")
    public Collection<UtenlandskId> getUtenlandskId() {
        return this.utenlandskId;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isErOpphørt() {
        return this.erOpphørt;
    }

    @java.lang.SuppressWarnings("all")
    public Kjønn getKjønn() {
        return this.kjønn;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PersonModell)) return false;
        final PersonModell other = (PersonModell) o;
        if (this.isErOpphørt() != other.isErOpphørt()) return false;
        final java.lang.Object this$ident = this.getIdent();
        final java.lang.Object other$ident = other.getIdent();
        if (this$ident == null ? other$ident != null : !this$ident.equals(other$ident)) return false;
        final java.lang.Object this$fornavn = this.getFornavn();
        final java.lang.Object other$fornavn = other.getFornavn();
        if (this$fornavn == null ? other$fornavn != null : !this$fornavn.equals(other$fornavn)) return false;
        final java.lang.Object this$etternavn = this.getEtternavn();
        final java.lang.Object other$etternavn = other.getEtternavn();
        if (this$etternavn == null ? other$etternavn != null : !this$etternavn.equals(other$etternavn)) return false;
        final java.lang.Object this$fødselsdato = this.getFødselsdato();
        final java.lang.Object other$fødselsdato = other.getFødselsdato();
        if (this$fødselsdato == null ? other$fødselsdato != null : !this$fødselsdato.equals(other$fødselsdato))
            return false;
        final java.lang.Object this$statsborgerskapLandkodeISO2 = this.getStatsborgerskapLandkodeISO2();
        final java.lang.Object other$statsborgerskapLandkodeISO2 = other.getStatsborgerskapLandkodeISO2();
        if (this$statsborgerskapLandkodeISO2 == null ? other$statsborgerskapLandkodeISO2 != null : !this$statsborgerskapLandkodeISO2.equals(other$statsborgerskapLandkodeISO2))
            return false;
        final java.lang.Object this$utenlandskId = this.getUtenlandskId();
        final java.lang.Object other$utenlandskId = other.getUtenlandskId();
        if (this$utenlandskId == null ? other$utenlandskId != null : !this$utenlandskId.equals(other$utenlandskId))
            return false;
        final java.lang.Object this$kjønn = this.getKjønn();
        final java.lang.Object other$kjønn = other.getKjønn();
        if (this$kjønn == null ? other$kjønn != null : !this$kjønn.equals(other$kjønn)) return false;
        return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isErOpphørt() ? 79 : 97);
        final java.lang.Object $ident = this.getIdent();
        result = result * PRIME + ($ident == null ? 43 : $ident.hashCode());
        final java.lang.Object $fornavn = this.getFornavn();
        result = result * PRIME + ($fornavn == null ? 43 : $fornavn.hashCode());
        final java.lang.Object $etternavn = this.getEtternavn();
        result = result * PRIME + ($etternavn == null ? 43 : $etternavn.hashCode());
        final java.lang.Object $fødselsdato = this.getFødselsdato();
        result = result * PRIME + ($fødselsdato == null ? 43 : $fødselsdato.hashCode());
        final java.lang.Object $statsborgerskapLandkodeISO2 = this.getStatsborgerskapLandkodeISO2();
        result = result * PRIME + ($statsborgerskapLandkodeISO2 == null ? 43 : $statsborgerskapLandkodeISO2.hashCode());
        final java.lang.Object $utenlandskId = this.getUtenlandskId();
        result = result * PRIME + ($utenlandskId == null ? 43 : $utenlandskId.hashCode());
        final java.lang.Object $kjønn = this.getKjønn();
        result = result * PRIME + ($kjønn == null ? 43 : $kjønn.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PersonModell(ident=" + this.getIdent() + ", fornavn=" + this.getFornavn() + ", etternavn=" + this.getEtternavn() + ", fødselsdato=" + this.getFødselsdato() + ", statsborgerskapLandkodeISO2=" + this.getStatsborgerskapLandkodeISO2() + ", utenlandskId=" + this.getUtenlandskId() + ", erOpphørt=" + this.isErOpphørt() + ", kjønn=" + this.getKjønn() + ")";
    }
}
