// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.kafka.producers.model;

import org.apache.commons.lang3.StringUtils;
import java.util.List;

public class Arbeidsland {
    private String land;
    private List<Arbeidssted> arbeidssted;

    public Arbeidsland(no.nav.melosys.eessi.models.sed.nav.Arbeidsland arbeidsland) {
        this(arbeidsland.getLand(), arbeidsland.getArbeidssted().stream().map(Arbeidssted::new).toList());
    }

    @java.lang.SuppressWarnings("all")
    public String getLand() {
        return this.land;
    }

    @java.lang.SuppressWarnings("all")
    public List<Arbeidssted> getArbeidssted() {
        return this.arbeidssted;
    }

    @java.lang.SuppressWarnings("all")
    public void setLand(final String land) {
        this.land = land;
    }

    @java.lang.SuppressWarnings("all")
    public void setArbeidssted(final List<Arbeidssted> arbeidssted) {
        this.arbeidssted = arbeidssted;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Arbeidsland)) return false;
        final Arbeidsland other = (Arbeidsland) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$land = this.getLand();
        final java.lang.Object other$land = other.getLand();
        if (this$land == null ? other$land != null : !this$land.equals(other$land)) return false;
        final java.lang.Object this$arbeidssted = this.getArbeidssted();
        final java.lang.Object other$arbeidssted = other.getArbeidssted();
        if (this$arbeidssted == null ? other$arbeidssted != null : !this$arbeidssted.equals(other$arbeidssted)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Arbeidsland;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $land = this.getLand();
        result = result * PRIME + ($land == null ? 43 : $land.hashCode());
        final java.lang.Object $arbeidssted = this.getArbeidssted();
        result = result * PRIME + ($arbeidssted == null ? 43 : $arbeidssted.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Arbeidsland(land=" + this.getLand() + ", arbeidssted=" + this.getArbeidssted() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Arbeidsland(final String land, final List<Arbeidssted> arbeidssted) {
        this.land = land;
        this.arbeidssted = arbeidssted;
    }
}
