// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.kafka.producers.model;

public class Avsender {
    private String avsenderID;
    private String landkode;

    @java.lang.SuppressWarnings("all")
    public String getAvsenderID() {
        return this.avsenderID;
    }

    @java.lang.SuppressWarnings("all")
    public String getLandkode() {
        return this.landkode;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvsenderID(final String avsenderID) {
        this.avsenderID = avsenderID;
    }

    @java.lang.SuppressWarnings("all")
    public void setLandkode(final String landkode) {
        this.landkode = landkode;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Avsender)) return false;
        final Avsender other = (Avsender) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$avsenderID = this.getAvsenderID();
        final java.lang.Object other$avsenderID = other.getAvsenderID();
        if (this$avsenderID == null ? other$avsenderID != null : !this$avsenderID.equals(other$avsenderID)) return false;
        final java.lang.Object this$landkode = this.getLandkode();
        final java.lang.Object other$landkode = other.getLandkode();
        if (this$landkode == null ? other$landkode != null : !this$landkode.equals(other$landkode)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Avsender;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $avsenderID = this.getAvsenderID();
        result = result * PRIME + ($avsenderID == null ? 43 : $avsenderID.hashCode());
        final java.lang.Object $landkode = this.getLandkode();
        result = result * PRIME + ($landkode == null ? 43 : $landkode.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Avsender(avsenderID=" + this.getAvsenderID() + ", landkode=" + this.getLandkode() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public Avsender() {
    }

    @java.lang.SuppressWarnings("all")
    public Avsender(final String avsenderID, final String landkode) {
        this.avsenderID = avsenderID;
        this.landkode = landkode;
    }
}
