// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.common.graphql.response;

import java.util.List;
import java.util.stream.Collectors;
import org.springframework.util.CollectionUtils;

public class GraphQLResponse<T> {
    private List<GraphQLError> errors;
    private T data;

    public boolean harFeil() {
        return !CollectionUtils.isEmpty(errors) || data == null;
    }

    public String lagErrorString() {
        return errors.stream().map(GraphQLError::getMessage).collect(Collectors.joining("\n"));
    }

    @java.lang.SuppressWarnings("all")
    public GraphQLResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public List<GraphQLError> getErrors() {
        return this.errors;
    }

    @java.lang.SuppressWarnings("all")
    public T getData() {
        return this.data;
    }

    @java.lang.SuppressWarnings("all")
    public void setErrors(final List<GraphQLError> errors) {
        this.errors = errors;
    }

    @java.lang.SuppressWarnings("all")
    public void setData(final T data) {
        this.data = data;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof GraphQLResponse)) return false;
        final GraphQLResponse<?> other = (GraphQLResponse<?>) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$errors = this.getErrors();
        final java.lang.Object other$errors = other.getErrors();
        if (this$errors == null ? other$errors != null : !this$errors.equals(other$errors)) return false;
        final java.lang.Object this$data = this.getData();
        final java.lang.Object other$data = other.getData();
        if (this$data == null ? other$data != null : !this$data.equals(other$data)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof GraphQLResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $errors = this.getErrors();
        result = result * PRIME + ($errors == null ? 43 : $errors.hashCode());
        final java.lang.Object $data = this.getData();
        result = result * PRIME + ($data == null ? 43 : $data.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "GraphQLResponse(errors=" + this.getErrors() + ", data=" + this.getData() + ")";
    }
}
