// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.kafka.consumers;

import java.util.List;
import java.util.stream.Stream;
import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.*;
import no.nav.melosys.eessi.models.SedType;

public class SedHendelse {
    private static final List<String> TRENGER_KONTROLL = Stream.of(SedType.X001, SedType.X006, SedType.X007, SedType.X008).map(Enum::name).toList();
    private long id;
    private String sedId;
    private String sektorKode;
    private String bucType;
    private String rinaSakId;
    private String avsenderId;
    private String avsenderNavn;
    private String mottakerId;
    private String mottakerNavn;
    private String rinaDokumentId;
    private String rinaDokumentVersjon;
    private String sedType;
    private String navBruker;

    // avsenderID har formatet <landkodeISO2>:<institusjonID>
    @JsonIgnore
    public String getLandkode() {
        return avsenderId.substring(0, 2);
    }

    @JsonIgnore
    public String getInstitusjon() {
        return avsenderId;
    }

    @JsonIgnore
    public boolean erX100() {
        return sedType.equals(SedType.X100.name());
    }

    @JsonIgnore
    public boolean erASED() {
        return SedType.valueOf(sedType).erASED();
    }

    @JsonIgnore
    public boolean erXSedSomTrengerKontroll() {
        return TRENGER_KONTROLL.contains(sedType.toUpperCase());
    }

    @JsonIgnore
    public boolean erIkkeLaBuc() {
        return !"LA".equals(getSektorKode());
    }


    @java.lang.SuppressWarnings("all")
    public static class SedHendelseBuilder {
        @java.lang.SuppressWarnings("all")
        private long id;
        @java.lang.SuppressWarnings("all")
        private String sedId;
        @java.lang.SuppressWarnings("all")
        private String sektorKode;
        @java.lang.SuppressWarnings("all")
        private String bucType;
        @java.lang.SuppressWarnings("all")
        private String rinaSakId;
        @java.lang.SuppressWarnings("all")
        private String avsenderId;
        @java.lang.SuppressWarnings("all")
        private String avsenderNavn;
        @java.lang.SuppressWarnings("all")
        private String mottakerId;
        @java.lang.SuppressWarnings("all")
        private String mottakerNavn;
        @java.lang.SuppressWarnings("all")
        private String rinaDokumentId;
        @java.lang.SuppressWarnings("all")
        private String rinaDokumentVersjon;
        @java.lang.SuppressWarnings("all")
        private String sedType;
        @java.lang.SuppressWarnings("all")
        private String navBruker;

        @java.lang.SuppressWarnings("all")
        SedHendelseBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SedHendelse.SedHendelseBuilder id(final long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SedHendelse.SedHendelseBuilder sedId(final String sedId) {
            this.sedId = sedId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SedHendelse.SedHendelseBuilder sektorKode(final String sektorKode) {
            this.sektorKode = sektorKode;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SedHendelse.SedHendelseBuilder bucType(final String bucType) {
            this.bucType = bucType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SedHendelse.SedHendelseBuilder rinaSakId(final String rinaSakId) {
            this.rinaSakId = rinaSakId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SedHendelse.SedHendelseBuilder avsenderId(final String avsenderId) {
            this.avsenderId = avsenderId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SedHendelse.SedHendelseBuilder avsenderNavn(final String avsenderNavn) {
            this.avsenderNavn = avsenderNavn;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SedHendelse.SedHendelseBuilder mottakerId(final String mottakerId) {
            this.mottakerId = mottakerId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SedHendelse.SedHendelseBuilder mottakerNavn(final String mottakerNavn) {
            this.mottakerNavn = mottakerNavn;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SedHendelse.SedHendelseBuilder rinaDokumentId(final String rinaDokumentId) {
            this.rinaDokumentId = rinaDokumentId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SedHendelse.SedHendelseBuilder rinaDokumentVersjon(final String rinaDokumentVersjon) {
            this.rinaDokumentVersjon = rinaDokumentVersjon;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SedHendelse.SedHendelseBuilder sedType(final String sedType) {
            this.sedType = sedType;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public SedHendelse.SedHendelseBuilder navBruker(final String navBruker) {
            this.navBruker = navBruker;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public SedHendelse build() {
            return new SedHendelse(this.id, this.sedId, this.sektorKode, this.bucType, this.rinaSakId, this.avsenderId, this.avsenderNavn, this.mottakerId, this.mottakerNavn, this.rinaDokumentId, this.rinaDokumentVersjon, this.sedType, this.navBruker);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "SedHendelse.SedHendelseBuilder(id=" + this.id + ", sedId=" + this.sedId + ", sektorKode=" + this.sektorKode + ", bucType=" + this.bucType + ", rinaSakId=" + this.rinaSakId + ", avsenderId=" + this.avsenderId + ", avsenderNavn=" + this.avsenderNavn + ", mottakerId=" + this.mottakerId + ", mottakerNavn=" + this.mottakerNavn + ", rinaDokumentId=" + this.rinaDokumentId + ", rinaDokumentVersjon=" + this.rinaDokumentVersjon + ", sedType=" + this.sedType + ", navBruker=" + this.navBruker + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static SedHendelse.SedHendelseBuilder builder() {
        return new SedHendelse.SedHendelseBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public SedHendelse(final long id, final String sedId, final String sektorKode, final String bucType, final String rinaSakId, final String avsenderId, final String avsenderNavn, final String mottakerId, final String mottakerNavn, final String rinaDokumentId, final String rinaDokumentVersjon, final String sedType, final String navBruker) {
        this.id = id;
        this.sedId = sedId;
        this.sektorKode = sektorKode;
        this.bucType = bucType;
        this.rinaSakId = rinaSakId;
        this.avsenderId = avsenderId;
        this.avsenderNavn = avsenderNavn;
        this.mottakerId = mottakerId;
        this.mottakerNavn = mottakerNavn;
        this.rinaDokumentId = rinaDokumentId;
        this.rinaDokumentVersjon = rinaDokumentVersjon;
        this.sedType = sedType;
        this.navBruker = navBruker;
    }

    @java.lang.SuppressWarnings("all")
    public SedHendelse() {
    }

    @java.lang.SuppressWarnings("all")
    public long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getSedId() {
        return this.sedId;
    }

    @java.lang.SuppressWarnings("all")
    public String getSektorKode() {
        return this.sektorKode;
    }

    @java.lang.SuppressWarnings("all")
    public String getBucType() {
        return this.bucType;
    }

    @java.lang.SuppressWarnings("all")
    public String getRinaSakId() {
        return this.rinaSakId;
    }

    @java.lang.SuppressWarnings("all")
    public String getAvsenderId() {
        return this.avsenderId;
    }

    @java.lang.SuppressWarnings("all")
    public String getAvsenderNavn() {
        return this.avsenderNavn;
    }

    @java.lang.SuppressWarnings("all")
    public String getMottakerId() {
        return this.mottakerId;
    }

    @java.lang.SuppressWarnings("all")
    public String getMottakerNavn() {
        return this.mottakerNavn;
    }

    @java.lang.SuppressWarnings("all")
    public String getRinaDokumentId() {
        return this.rinaDokumentId;
    }

    @java.lang.SuppressWarnings("all")
    public String getRinaDokumentVersjon() {
        return this.rinaDokumentVersjon;
    }

    @java.lang.SuppressWarnings("all")
    public String getSedType() {
        return this.sedType;
    }

    @java.lang.SuppressWarnings("all")
    public String getNavBruker() {
        return this.navBruker;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setSedId(final String sedId) {
        this.sedId = sedId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSektorKode(final String sektorKode) {
        this.sektorKode = sektorKode;
    }

    @java.lang.SuppressWarnings("all")
    public void setBucType(final String bucType) {
        this.bucType = bucType;
    }

    @java.lang.SuppressWarnings("all")
    public void setRinaSakId(final String rinaSakId) {
        this.rinaSakId = rinaSakId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvsenderId(final String avsenderId) {
        this.avsenderId = avsenderId;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvsenderNavn(final String avsenderNavn) {
        this.avsenderNavn = avsenderNavn;
    }

    @java.lang.SuppressWarnings("all")
    public void setMottakerId(final String mottakerId) {
        this.mottakerId = mottakerId;
    }

    @java.lang.SuppressWarnings("all")
    public void setMottakerNavn(final String mottakerNavn) {
        this.mottakerNavn = mottakerNavn;
    }

    @java.lang.SuppressWarnings("all")
    public void setRinaDokumentId(final String rinaDokumentId) {
        this.rinaDokumentId = rinaDokumentId;
    }

    @java.lang.SuppressWarnings("all")
    public void setRinaDokumentVersjon(final String rinaDokumentVersjon) {
        this.rinaDokumentVersjon = rinaDokumentVersjon;
    }

    @java.lang.SuppressWarnings("all")
    public void setSedType(final String sedType) {
        this.sedType = sedType;
    }

    @java.lang.SuppressWarnings("all")
    public void setNavBruker(final String navBruker) {
        this.navBruker = navBruker;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SedHendelse)) return false;
        final SedHendelse other = (SedHendelse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getId() != other.getId()) return false;
        final java.lang.Object this$sedId = this.getSedId();
        final java.lang.Object other$sedId = other.getSedId();
        if (this$sedId == null ? other$sedId != null : !this$sedId.equals(other$sedId)) return false;
        final java.lang.Object this$sektorKode = this.getSektorKode();
        final java.lang.Object other$sektorKode = other.getSektorKode();
        if (this$sektorKode == null ? other$sektorKode != null : !this$sektorKode.equals(other$sektorKode)) return false;
        final java.lang.Object this$bucType = this.getBucType();
        final java.lang.Object other$bucType = other.getBucType();
        if (this$bucType == null ? other$bucType != null : !this$bucType.equals(other$bucType)) return false;
        final java.lang.Object this$rinaSakId = this.getRinaSakId();
        final java.lang.Object other$rinaSakId = other.getRinaSakId();
        if (this$rinaSakId == null ? other$rinaSakId != null : !this$rinaSakId.equals(other$rinaSakId)) return false;
        final java.lang.Object this$avsenderId = this.getAvsenderId();
        final java.lang.Object other$avsenderId = other.getAvsenderId();
        if (this$avsenderId == null ? other$avsenderId != null : !this$avsenderId.equals(other$avsenderId)) return false;
        final java.lang.Object this$avsenderNavn = this.getAvsenderNavn();
        final java.lang.Object other$avsenderNavn = other.getAvsenderNavn();
        if (this$avsenderNavn == null ? other$avsenderNavn != null : !this$avsenderNavn.equals(other$avsenderNavn)) return false;
        final java.lang.Object this$mottakerId = this.getMottakerId();
        final java.lang.Object other$mottakerId = other.getMottakerId();
        if (this$mottakerId == null ? other$mottakerId != null : !this$mottakerId.equals(other$mottakerId)) return false;
        final java.lang.Object this$mottakerNavn = this.getMottakerNavn();
        final java.lang.Object other$mottakerNavn = other.getMottakerNavn();
        if (this$mottakerNavn == null ? other$mottakerNavn != null : !this$mottakerNavn.equals(other$mottakerNavn)) return false;
        final java.lang.Object this$rinaDokumentId = this.getRinaDokumentId();
        final java.lang.Object other$rinaDokumentId = other.getRinaDokumentId();
        if (this$rinaDokumentId == null ? other$rinaDokumentId != null : !this$rinaDokumentId.equals(other$rinaDokumentId)) return false;
        final java.lang.Object this$rinaDokumentVersjon = this.getRinaDokumentVersjon();
        final java.lang.Object other$rinaDokumentVersjon = other.getRinaDokumentVersjon();
        if (this$rinaDokumentVersjon == null ? other$rinaDokumentVersjon != null : !this$rinaDokumentVersjon.equals(other$rinaDokumentVersjon)) return false;
        final java.lang.Object this$sedType = this.getSedType();
        final java.lang.Object other$sedType = other.getSedType();
        if (this$sedType == null ? other$sedType != null : !this$sedType.equals(other$sedType)) return false;
        final java.lang.Object this$navBruker = this.getNavBruker();
        final java.lang.Object other$navBruker = other.getNavBruker();
        if (this$navBruker == null ? other$navBruker != null : !this$navBruker.equals(other$navBruker)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SedHendelse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final long $id = this.getId();
        result = result * PRIME + (int) ($id >>> 32 ^ $id);
        final java.lang.Object $sedId = this.getSedId();
        result = result * PRIME + ($sedId == null ? 43 : $sedId.hashCode());
        final java.lang.Object $sektorKode = this.getSektorKode();
        result = result * PRIME + ($sektorKode == null ? 43 : $sektorKode.hashCode());
        final java.lang.Object $bucType = this.getBucType();
        result = result * PRIME + ($bucType == null ? 43 : $bucType.hashCode());
        final java.lang.Object $rinaSakId = this.getRinaSakId();
        result = result * PRIME + ($rinaSakId == null ? 43 : $rinaSakId.hashCode());
        final java.lang.Object $avsenderId = this.getAvsenderId();
        result = result * PRIME + ($avsenderId == null ? 43 : $avsenderId.hashCode());
        final java.lang.Object $avsenderNavn = this.getAvsenderNavn();
        result = result * PRIME + ($avsenderNavn == null ? 43 : $avsenderNavn.hashCode());
        final java.lang.Object $mottakerId = this.getMottakerId();
        result = result * PRIME + ($mottakerId == null ? 43 : $mottakerId.hashCode());
        final java.lang.Object $mottakerNavn = this.getMottakerNavn();
        result = result * PRIME + ($mottakerNavn == null ? 43 : $mottakerNavn.hashCode());
        final java.lang.Object $rinaDokumentId = this.getRinaDokumentId();
        result = result * PRIME + ($rinaDokumentId == null ? 43 : $rinaDokumentId.hashCode());
        final java.lang.Object $rinaDokumentVersjon = this.getRinaDokumentVersjon();
        result = result * PRIME + ($rinaDokumentVersjon == null ? 43 : $rinaDokumentVersjon.hashCode());
        final java.lang.Object $sedType = this.getSedType();
        result = result * PRIME + ($sedType == null ? 43 : $sedType.hashCode());
        final java.lang.Object $navBruker = this.getNavBruker();
        result = result * PRIME + ($navBruker == null ? 43 : $navBruker.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SedHendelse(id=" + this.getId() + ", sedId=" + this.getSedId() + ", sektorKode=" + this.getSektorKode() + ", bucType=" + this.getBucType() + ", rinaSakId=" + this.getRinaSakId() + ", avsenderId=" + this.getAvsenderId() + ", avsenderNavn=" + this.getAvsenderNavn() + ", mottakerId=" + this.getMottakerId() + ", mottakerNavn=" + this.getMottakerNavn() + ", rinaDokumentId=" + this.getRinaDokumentId() + ", rinaDokumentVersjon=" + this.getRinaDokumentVersjon() + ", sedType=" + this.getSedType() + ")";
    }
}
