// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.controller;

import java.util.UUID;

import no.nav.melosys.eessi.integration.journalpostapi.SedAlleredeJournalførtException;
import no.nav.melosys.eessi.kafka.consumers.SedHendelse;
import no.nav.melosys.eessi.metrikker.SedMetrikker;
import no.nav.melosys.eessi.models.SedMottattHendelse;
import no.nav.melosys.eessi.service.mottak.SedMottakService;
import no.nav.security.token.support.core.api.Protected;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import static no.nav.melosys.eessi.config.MDCOperations.*;

@Protected
@RestController
@RequestMapping("/admin/sedmottatt")
public class SedMottattAdminTjeneste {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(SedMottattAdminTjeneste.class);
    private final SedMottakService sedMottakService;
    private final SedMetrikker sedMetrikker;

    public SedMottattAdminTjeneste(SedMottakService sedMottakService, SedMetrikker sedMetrikker) {
        this.sedMottakService = sedMottakService;
        this.sedMetrikker = sedMetrikker;
    }

    @PostMapping("")
    public ResponseEntity<String> leggTilSedHendelse(@RequestBody SedHendelse sedHendelse) {
        sedMottatt(sedHendelse);
        return ResponseEntity.status(200).build();
    }

    private void sedMottatt(SedHendelse sedHendelse) {
        putToMDC(SED_ID, sedHendelse.getSedId());
        putToMDC(CORRELATION_ID, UUID.randomUUID().toString());
        log.info("Sed mottatt fra SedMottattAdminTjeneste : {}", sedHendelse);
        try {
            sedMottakService.behandleSedMottakHendelse(SedMottattHendelse.builder().sedHendelse(sedHendelse).build());
        } catch (SedAlleredeJournalførtException e) {
            log.warn("SED {} allerede journalført", e.getSedID());
            sedMetrikker.sedMottattAlleredejournalfoert(sedHendelse.getSedType());
        } catch (Exception e) {
            sedMetrikker.sedMottattFeilet(sedHendelse.getSedType());
            String message = e.getMessage() != null ? e.getMessage() : e.getClass().getSimpleName();
            log.error("sedMottatt feilet: {}\n{}", message, sedHendelse, e);
            throw e;
        } finally {
            remove(SED_ID);
            remove(CORRELATION_ID);
        }
    }
}
