// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.web.identrekvisisjon.dto.adresse;

public class IdentRekvisisjonAdresse {
    String adressegradering;
    String adresseIdentifikatorFraMatrikkelen;
    String naerAdresseIdentifikatorFraMatrikkelen;
    String bruksenhetsnummer;
    String coAdressenavn;
    Long grunnkrets;
    UkjentBosted ukjentBosted;
    Vegadresse vegadresse;
    Matrikkeladresse matrikkeladresse;
    UtenlandskAdresse utenlandskAdresse;
    UtenlandskAdresseIFrittFormat utenlandskAdresseIFrittFormat;
    Postboksadresse postboksadresse;
    VegadresseForPost vegadresseForPost;
    PostadresseIFrittFormat postadresseIFrittFormat;

    @java.lang.SuppressWarnings("all")
    public String getAdressegradering() {
        return this.adressegradering;
    }

    @java.lang.SuppressWarnings("all")
    public String getAdresseIdentifikatorFraMatrikkelen() {
        return this.adresseIdentifikatorFraMatrikkelen;
    }

    @java.lang.SuppressWarnings("all")
    public String getNaerAdresseIdentifikatorFraMatrikkelen() {
        return this.naerAdresseIdentifikatorFraMatrikkelen;
    }

    @java.lang.SuppressWarnings("all")
    public String getBruksenhetsnummer() {
        return this.bruksenhetsnummer;
    }

    @java.lang.SuppressWarnings("all")
    public String getCoAdressenavn() {
        return this.coAdressenavn;
    }

    @java.lang.SuppressWarnings("all")
    public Long getGrunnkrets() {
        return this.grunnkrets;
    }

    @java.lang.SuppressWarnings("all")
    public UkjentBosted getUkjentBosted() {
        return this.ukjentBosted;
    }

    @java.lang.SuppressWarnings("all")
    public Vegadresse getVegadresse() {
        return this.vegadresse;
    }

    @java.lang.SuppressWarnings("all")
    public Matrikkeladresse getMatrikkeladresse() {
        return this.matrikkeladresse;
    }

    @java.lang.SuppressWarnings("all")
    public UtenlandskAdresse getUtenlandskAdresse() {
        return this.utenlandskAdresse;
    }

    @java.lang.SuppressWarnings("all")
    public UtenlandskAdresseIFrittFormat getUtenlandskAdresseIFrittFormat() {
        return this.utenlandskAdresseIFrittFormat;
    }

    @java.lang.SuppressWarnings("all")
    public Postboksadresse getPostboksadresse() {
        return this.postboksadresse;
    }

    @java.lang.SuppressWarnings("all")
    public VegadresseForPost getVegadresseForPost() {
        return this.vegadresseForPost;
    }

    @java.lang.SuppressWarnings("all")
    public PostadresseIFrittFormat getPostadresseIFrittFormat() {
        return this.postadresseIFrittFormat;
    }

    @java.lang.SuppressWarnings("all")
    public IdentRekvisisjonAdresse(final String adressegradering, final String adresseIdentifikatorFraMatrikkelen, final String naerAdresseIdentifikatorFraMatrikkelen, final String bruksenhetsnummer, final String coAdressenavn, final Long grunnkrets, final UkjentBosted ukjentBosted, final Vegadresse vegadresse, final Matrikkeladresse matrikkeladresse, final UtenlandskAdresse utenlandskAdresse, final UtenlandskAdresseIFrittFormat utenlandskAdresseIFrittFormat, final Postboksadresse postboksadresse, final VegadresseForPost vegadresseForPost, final PostadresseIFrittFormat postadresseIFrittFormat) {
        this.adressegradering = adressegradering;
        this.adresseIdentifikatorFraMatrikkelen = adresseIdentifikatorFraMatrikkelen;
        this.naerAdresseIdentifikatorFraMatrikkelen = naerAdresseIdentifikatorFraMatrikkelen;
        this.bruksenhetsnummer = bruksenhetsnummer;
        this.coAdressenavn = coAdressenavn;
        this.grunnkrets = grunnkrets;
        this.ukjentBosted = ukjentBosted;
        this.vegadresse = vegadresse;
        this.matrikkeladresse = matrikkeladresse;
        this.utenlandskAdresse = utenlandskAdresse;
        this.utenlandskAdresseIFrittFormat = utenlandskAdresseIFrittFormat;
        this.postboksadresse = postboksadresse;
        this.vegadresseForPost = vegadresseForPost;
        this.postadresseIFrittFormat = postadresseIFrittFormat;
    }
}
