// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.web.identrekvisisjon.dto.adresse;

public class Matrikkeladresse {
    String bruksenhetstype;
    Integer undernummer;
    String adressetilleggsnavn;
    Matrikkelnummer matrikkelnummer;
    Poststed poststed;

    @java.lang.SuppressWarnings("all")
    public String getBruksenhetstype() {
        return this.bruksenhetstype;
    }

    @java.lang.SuppressWarnings("all")
    public Integer getUndernummer() {
        return this.undernummer;
    }

    @java.lang.SuppressWarnings("all")
    public String getAdressetilleggsnavn() {
        return this.adressetilleggsnavn;
    }

    @java.lang.SuppressWarnings("all")
    public Matrikkelnummer getMatrikkelnummer() {
        return this.matrikkelnummer;
    }

    @java.lang.SuppressWarnings("all")
    public Poststed getPoststed() {
        return this.poststed;
    }

    @java.lang.SuppressWarnings("all")
    public Matrikkeladresse(final String bruksenhetstype, final Integer undernummer, final String adressetilleggsnavn, final Matrikkelnummer matrikkelnummer, final Poststed poststed) {
        this.bruksenhetstype = bruksenhetstype;
        this.undernummer = undernummer;
        this.adressetilleggsnavn = adressetilleggsnavn;
        this.matrikkelnummer = matrikkelnummer;
        this.poststed = poststed;
    }
}
