// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.web.identrekvisisjon.dto.adresse;

public class UtenlandskAdresse {
    String adressenavnNummer;
    String bygningEtasjeLeilighet;
    String bygning;
    String etasjenummer;
    String boenhet;
    String postboksNummerNavn;
    String postkode;
    String bySted;
    String regionDistriktOmraade;
    String distriktsnavn;
    String region;
    String landkode;

    @java.lang.SuppressWarnings("all")
    public String getAdressenavnNummer() {
        return this.adressenavnNummer;
    }

    @java.lang.SuppressWarnings("all")
    public String getBygningEtasjeLeilighet() {
        return this.bygningEtasjeLeilighet;
    }

    @java.lang.SuppressWarnings("all")
    public String getBygning() {
        return this.bygning;
    }

    @java.lang.SuppressWarnings("all")
    public String getEtasjenummer() {
        return this.etasjenummer;
    }

    @java.lang.SuppressWarnings("all")
    public String getBoenhet() {
        return this.boenhet;
    }

    @java.lang.SuppressWarnings("all")
    public String getPostboksNummerNavn() {
        return this.postboksNummerNavn;
    }

    @java.lang.SuppressWarnings("all")
    public String getPostkode() {
        return this.postkode;
    }

    @java.lang.SuppressWarnings("all")
    public String getBySted() {
        return this.bySted;
    }

    @java.lang.SuppressWarnings("all")
    public String getRegionDistriktOmraade() {
        return this.regionDistriktOmraade;
    }

    @java.lang.SuppressWarnings("all")
    public String getDistriktsnavn() {
        return this.distriktsnavn;
    }

    @java.lang.SuppressWarnings("all")
    public String getRegion() {
        return this.region;
    }

    @java.lang.SuppressWarnings("all")
    public String getLandkode() {
        return this.landkode;
    }

    @java.lang.SuppressWarnings("all")
    public UtenlandskAdresse(final String adressenavnNummer, final String bygningEtasjeLeilighet, final String bygning, final String etasjenummer, final String boenhet, final String postboksNummerNavn, final String postkode, final String bySted, final String regionDistriktOmraade, final String distriktsnavn, final String region, final String landkode) {
        this.adressenavnNummer = adressenavnNummer;
        this.bygningEtasjeLeilighet = bygningEtasjeLeilighet;
        this.bygning = bygning;
        this.etasjenummer = etasjenummer;
        this.boenhet = boenhet;
        this.postboksNummerNavn = postboksNummerNavn;
        this.postkode = postkode;
        this.bySted = bySted;
        this.regionDistriktOmraade = regionDistriktOmraade;
        this.distriktsnavn = distriktsnavn;
        this.region = region;
        this.landkode = landkode;
    }
}
