// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.web.identrekvisisjon.dto.adresse;

import java.util.List;

public class UtenlandskAdresseIFrittFormat {
    List<String> adresselinje;
    String postkode;
    String byEllerStedsnavn;
    String landkode;

    @java.lang.SuppressWarnings("all")
    public List<String> getAdresselinje() {
        return this.adresselinje;
    }

    @java.lang.SuppressWarnings("all")
    public String getPostkode() {
        return this.postkode;
    }

    @java.lang.SuppressWarnings("all")
    public String getByEllerStedsnavn() {
        return this.byEllerStedsnavn;
    }

    @java.lang.SuppressWarnings("all")
    public String getLandkode() {
        return this.landkode;
    }

    @java.lang.SuppressWarnings("all")
    public UtenlandskAdresseIFrittFormat(final List<String> adresselinje, final String postkode, final String byEllerStedsnavn, final String landkode) {
        this.adresselinje = adresselinje;
        this.postkode = postkode;
        this.byEllerStedsnavn = byEllerStedsnavn;
        this.landkode = landkode;
    }
}
