// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.web.identrekvisisjon.dto.adresse;

import lombok.Builder;
import lombok.Value;

public class VegadresseForPost {
    String adressenavn;
    Adressenummer adressenummer;
    String adressekode;
    String adressetilleggsnavn;
    Poststed poststed;

    @java.lang.SuppressWarnings("all")
    public String getAdressenavn() {
        return this.adressenavn;
    }

    @java.lang.SuppressWarnings("all")
    public Adressenummer getAdressenummer() {
        return this.adressenummer;
    }

    @java.lang.SuppressWarnings("all")
    public String getAdressekode() {
        return this.adressekode;
    }

    @java.lang.SuppressWarnings("all")
    public String getAdressetilleggsnavn() {
        return this.adressetilleggsnavn;
    }

    @java.lang.SuppressWarnings("all")
    public Poststed getPoststed() {
        return this.poststed;
    }

    @java.lang.SuppressWarnings("all")
    public VegadresseForPost(final String adressenavn, final Adressenummer adressenummer, final String adressekode, final String adressetilleggsnavn, final Poststed poststed) {
        this.adressenavn = adressenavn;
        this.adressenummer = adressenummer;
        this.adressekode = adressekode;
        this.adressetilleggsnavn = adressetilleggsnavn;
        this.poststed = poststed;
    }
}
