// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.service.sak;

import no.nav.melosys.eessi.integration.sak.Sak;
import no.nav.melosys.eessi.integration.sak.SakConsumer;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

@Service
public class ArkivsakService {
    @java.lang.SuppressWarnings("all")
    private static final org.slf4j.Logger log = org.slf4j.LoggerFactory.getLogger(ArkivsakService.class);
    private final SakConsumer sakConsumer;

    @Autowired
    public ArkivsakService(SakConsumer sakConsumer) {
        this.sakConsumer = sakConsumer;
    }

    public Sak hentsak(Long id) {
        return sakConsumer.getSak(Long.toString(id));
    }
}
