server:
  port: 8080

spring:
  application:
    name: melosys-eessi
  datasource:
    url: jdbc:postgresql://${PG_HOST}:5432/${DATABASE_NAME}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true #fix for jdbc bug i postgres-driver som krasjer app
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        enable.idempotence: true

    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    properties:
      security.protocol: SASL_SSL
      sasl.mechanism: PLAIN
      sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required username="${melosys.systemuser.username}" password="${melosys.systemuser.password}";
      reconnect.backoff.ms: 1000

  servlet:
    multipart:
      max-file-size: 10485760 # 10MB
      max-request-size: 10485760 # 10MB

melosys:
  feature:
    nyttMottak: ${FEATURE_NYTT_MOTTAK:false}
  kafka:
    consumer:
      mottatt:
        topic: ${KAFKA_SEDMOTTATT_TOPIC:eessi-basis-sedMottatt-v1}
      sendt:
        topic: ${KAFKA_SEDSENDT_TOPIC:eessi-basis-sedSendt-v1}
      groupid: ${KAFKA_SEDHENDELSER_GROUPID:melosys-eessi-sedHendelser}
    producer:
      topic-name: ${KAFKA_EESSIMELDING_TOPIC}
  systemuser:
    username: ${SRV_USERNAME}
    password: ${SRV_PASSWORD}
  integrations:
    euxapp-url: ${EUXAPP_URL}
    reststs-url: ${RESTSTS_URL}
    rina-host-url: ${RINA_HOST_URL}
    journalpostapi-url: ${JOURNALPOSTAPI_URL}
    eux-case-store-url: ${EUXCASESTORE_URL}
    saf-url: ${SAF_URL}
    pdl-url: ${PDL_URL}

    dokkat:
      typeid-url: ${DOKKATTYPEID_URL}
      typeinfo-url: ${DOKKATTYPEINFO_URL}
    gsak:
      sak-url: ${SAK_URL}
      oppgave-url: ${OPPGAVE_URL}

management:
  metrics:
    web:
      server:
        auto-time-requests: true
    enable:
      jvm:
        threads.peak: false
        threads.deamon: false
        classes.loaded: false
        classes.unloaded: false
      process.start.time: false
  endpoints:
    web:
      exposure:
        include: health,prometheus
      base-path: /internal

#Token-validering
no.nav.security.jwt.issuer:
  reststs:
    discovery-url: ${RESTSTS_URL}/.well-known/openid-configuration
    accepted-audience: srvmelosys
  isso:
    discovery-url: ${ISSO_URL}/.well-known/openid-configuration
    accepted-audience: ${ISSO_ACCEPTED_AUDIENCE}
    cookie-name: ID_token
