// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models;

import jakarta.persistence.*;

@Entity(name = "buc_identifisering_oppg")
public class BucIdentifiseringOppg {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id")
    private Long id;
    @Column(name = "rina_saksnummer")
    private String rinaSaksnummer;
    @Column(name = "oppgave_id")
    private String oppgaveId;
    @Column(name = "versjon")
    private int versjon;


    @java.lang.SuppressWarnings("all")
    public static class BucIdentifiseringOppgBuilder {
        @java.lang.SuppressWarnings("all")
        private Long id;
        @java.lang.SuppressWarnings("all")
        private String rinaSaksnummer;
        @java.lang.SuppressWarnings("all")
        private String oppgaveId;
        @java.lang.SuppressWarnings("all")
        private int versjon;

        @java.lang.SuppressWarnings("all")
        BucIdentifiseringOppgBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public BucIdentifiseringOppg.BucIdentifiseringOppgBuilder id(final Long id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public BucIdentifiseringOppg.BucIdentifiseringOppgBuilder rinaSaksnummer(final String rinaSaksnummer) {
            this.rinaSaksnummer = rinaSaksnummer;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public BucIdentifiseringOppg.BucIdentifiseringOppgBuilder oppgaveId(final String oppgaveId) {
            this.oppgaveId = oppgaveId;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public BucIdentifiseringOppg.BucIdentifiseringOppgBuilder versjon(final int versjon) {
            this.versjon = versjon;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public BucIdentifiseringOppg build() {
            return new BucIdentifiseringOppg(this.id, this.rinaSaksnummer, this.oppgaveId, this.versjon);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "BucIdentifiseringOppg.BucIdentifiseringOppgBuilder(id=" + this.id + ", rinaSaksnummer=" + this.rinaSaksnummer + ", oppgaveId=" + this.oppgaveId + ", versjon=" + this.versjon + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static BucIdentifiseringOppg.BucIdentifiseringOppgBuilder builder() {
        return new BucIdentifiseringOppg.BucIdentifiseringOppgBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public Long getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getRinaSaksnummer() {
        return this.rinaSaksnummer;
    }

    @java.lang.SuppressWarnings("all")
    public String getOppgaveId() {
        return this.oppgaveId;
    }

    @java.lang.SuppressWarnings("all")
    public int getVersjon() {
        return this.versjon;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final Long id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setRinaSaksnummer(final String rinaSaksnummer) {
        this.rinaSaksnummer = rinaSaksnummer;
    }

    @java.lang.SuppressWarnings("all")
    public void setOppgaveId(final String oppgaveId) {
        this.oppgaveId = oppgaveId;
    }

    @java.lang.SuppressWarnings("all")
    public void setVersjon(final int versjon) {
        this.versjon = versjon;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "BucIdentifiseringOppg(id=" + this.getId() + ", rinaSaksnummer=" + this.getRinaSaksnummer() + ", oppgaveId=" + this.getOppgaveId() + ", versjon=" + this.getVersjon() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public BucIdentifiseringOppg() {
    }

    @java.lang.SuppressWarnings("all")
    public BucIdentifiseringOppg(final Long id, final String rinaSaksnummer, final String oppgaveId, final int versjon) {
        this.id = id;
        this.rinaSaksnummer = rinaSaksnummer;
        this.oppgaveId = oppgaveId;
        this.versjon = versjon;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof BucIdentifiseringOppg)) return false;
        final BucIdentifiseringOppg other = (BucIdentifiseringOppg) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.getVersjon() != other.getVersjon()) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$rinaSaksnummer = this.getRinaSaksnummer();
        final java.lang.Object other$rinaSaksnummer = other.getRinaSaksnummer();
        if (this$rinaSaksnummer == null ? other$rinaSaksnummer != null : !this$rinaSaksnummer.equals(other$rinaSaksnummer))
            return false;
        final java.lang.Object this$oppgaveId = this.getOppgaveId();
        final java.lang.Object other$oppgaveId = other.getOppgaveId();
        if (this$oppgaveId == null ? other$oppgaveId != null : !this$oppgaveId.equals(other$oppgaveId)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof BucIdentifiseringOppg;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getVersjon();
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $rinaSaksnummer = this.getRinaSaksnummer();
        result = result * PRIME + ($rinaSaksnummer == null ? 43 : $rinaSaksnummer.hashCode());
        final java.lang.Object $oppgaveId = this.getOppgaveId();
        result = result * PRIME + ($oppgaveId == null ? 43 : $oppgaveId.hashCode());
        return result;
    }
}
