// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;

@Entity(name = "JOURNALPOST_SED_KOBLING")
public class JournalpostSedKobling {
    @Id
    @Column(name = "journalpost_id")
    private String journalpostID;
    @Column(name = "rina_saksnummer")
    private String rinaSaksnummer;
    @Column(name = "sed_id")
    private String sedId;
    @Column(name = "sed_versjon")
    private String sedVersjon;
    @Column(name = "buc_type")
    private String bucType;
    @Column(name = "sed_type")
    private String sedType;

    public boolean erASed() {
        return sedType.toUpperCase().startsWith("A");
    }

    @java.lang.SuppressWarnings("all")
    public String getJournalpostID() {
        return this.journalpostID;
    }

    @java.lang.SuppressWarnings("all")
    public String getRinaSaksnummer() {
        return this.rinaSaksnummer;
    }

    @java.lang.SuppressWarnings("all")
    public String getSedId() {
        return this.sedId;
    }

    @java.lang.SuppressWarnings("all")
    public String getSedVersjon() {
        return this.sedVersjon;
    }

    @java.lang.SuppressWarnings("all")
    public String getBucType() {
        return this.bucType;
    }

    @java.lang.SuppressWarnings("all")
    public String getSedType() {
        return this.sedType;
    }

    @java.lang.SuppressWarnings("all")
    public void setJournalpostID(final String journalpostID) {
        this.journalpostID = journalpostID;
    }

    @java.lang.SuppressWarnings("all")
    public void setRinaSaksnummer(final String rinaSaksnummer) {
        this.rinaSaksnummer = rinaSaksnummer;
    }

    @java.lang.SuppressWarnings("all")
    public void setSedId(final String sedId) {
        this.sedId = sedId;
    }

    @java.lang.SuppressWarnings("all")
    public void setSedVersjon(final String sedVersjon) {
        this.sedVersjon = sedVersjon;
    }

    @java.lang.SuppressWarnings("all")
    public void setBucType(final String bucType) {
        this.bucType = bucType;
    }

    @java.lang.SuppressWarnings("all")
    public void setSedType(final String sedType) {
        this.sedType = sedType;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof JournalpostSedKobling)) return false;
        final JournalpostSedKobling other = (JournalpostSedKobling) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$journalpostID = this.getJournalpostID();
        final java.lang.Object other$journalpostID = other.getJournalpostID();
        if (this$journalpostID == null ? other$journalpostID != null : !this$journalpostID.equals(other$journalpostID))
            return false;
        final java.lang.Object this$rinaSaksnummer = this.getRinaSaksnummer();
        final java.lang.Object other$rinaSaksnummer = other.getRinaSaksnummer();
        if (this$rinaSaksnummer == null ? other$rinaSaksnummer != null : !this$rinaSaksnummer.equals(other$rinaSaksnummer))
            return false;
        final java.lang.Object this$sedId = this.getSedId();
        final java.lang.Object other$sedId = other.getSedId();
        if (this$sedId == null ? other$sedId != null : !this$sedId.equals(other$sedId)) return false;
        final java.lang.Object this$sedVersjon = this.getSedVersjon();
        final java.lang.Object other$sedVersjon = other.getSedVersjon();
        if (this$sedVersjon == null ? other$sedVersjon != null : !this$sedVersjon.equals(other$sedVersjon))
            return false;
        final java.lang.Object this$bucType = this.getBucType();
        final java.lang.Object other$bucType = other.getBucType();
        if (this$bucType == null ? other$bucType != null : !this$bucType.equals(other$bucType)) return false;
        final java.lang.Object this$sedType = this.getSedType();
        final java.lang.Object other$sedType = other.getSedType();
        if (this$sedType == null ? other$sedType != null : !this$sedType.equals(other$sedType)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof JournalpostSedKobling;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $journalpostID = this.getJournalpostID();
        result = result * PRIME + ($journalpostID == null ? 43 : $journalpostID.hashCode());
        final java.lang.Object $rinaSaksnummer = this.getRinaSaksnummer();
        result = result * PRIME + ($rinaSaksnummer == null ? 43 : $rinaSaksnummer.hashCode());
        final java.lang.Object $sedId = this.getSedId();
        result = result * PRIME + ($sedId == null ? 43 : $sedId.hashCode());
        final java.lang.Object $sedVersjon = this.getSedVersjon();
        result = result * PRIME + ($sedVersjon == null ? 43 : $sedVersjon.hashCode());
        final java.lang.Object $bucType = this.getBucType();
        result = result * PRIME + ($bucType == null ? 43 : $bucType.hashCode());
        final java.lang.Object $sedType = this.getSedType();
        result = result * PRIME + ($sedType == null ? 43 : $sedType.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "JournalpostSedKobling(journalpostID=" + this.getJournalpostID() + ", rinaSaksnummer=" + this.getRinaSaksnummer() + ", sedId=" + this.getSedId() + ", sedVersjon=" + this.getSedVersjon() + ", bucType=" + this.getBucType() + ", sedType=" + this.getSedType() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public JournalpostSedKobling(final String journalpostID, final String rinaSaksnummer, final String sedId, final String sedVersjon, final String bucType, final String sedType) {
        this.journalpostID = journalpostID;
        this.rinaSaksnummer = rinaSaksnummer;
        this.sedId = sedId;
        this.sedVersjon = sedVersjon;
        this.bucType = bucType;
        this.sedType = sedType;
    }

    @java.lang.SuppressWarnings("all")
    public JournalpostSedKobling() {
    }
}
