// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.service.sed

class SedMottattMigreringRapportDto(private val rinaSaksnummer: String?, private val dokumentId: String?, private val journalpostId: String?) {
    fun getRinaSaksnummer(): String? {
        return this.rinaSaksnummer
    }

    fun getDokumentId(): String? {
        return this.dokumentId
    }

    fun getJournalpostId(): String? {
        return this.journalpostId
    }

    override fun equals(o: Any?): Boolean {
        if (o === this) return true
        if (o !is SedMottattMigreringRapportDto) return false
        val other = o as SedMottattMigreringRapportDto
        if (!other.canEqual(this as Any)) return false
        val `this$rinaSaksnummer`: Any? = this.getRinaSaksnummer()
        val `other$rinaSaksnummer`: Any? = other.getRinaSaksnummer()
        if (if (`this$rinaSaksnummer` == null) `other$rinaSaksnummer` != null else (`this$rinaSaksnummer` != `other$rinaSaksnummer`)) return false
        val `this$dokumentId`: Any? = this.getDokumentId()
        val `other$dokumentId`: Any? = other.getDokumentId()
        if (if (`this$dokumentId` == null) `other$dokumentId` != null else (`this$dokumentId` != `other$dokumentId`)) return false
        val `this$journalpostId`: Any? = this.getJournalpostId()
        val `other$journalpostId`: Any? = other.getJournalpostId()
        if (if (`this$journalpostId` == null) `other$journalpostId` != null else (`this$journalpostId` != `other$journalpostId`)) return false
        return true
    }

    protected fun canEqual(other: Any?): Boolean {
        return other is SedMottattMigreringRapportDto
    }

    override fun hashCode(): Int {
        val PRIME = 59
        var result = 1
        val `$rinaSaksnummer`: Any? = this.getRinaSaksnummer()
        result = result * PRIME + (`$rinaSaksnummer`?.hashCode() ?: 43)
        val `$dokumentId`: Any? = this.getDokumentId()
        result = result * PRIME + (`$dokumentId`?.hashCode() ?: 43)
        val `$journalpostId`: Any? = this.getJournalpostId()
        result = result * PRIME + (`$journalpostId`?.hashCode() ?: 43)
        return result
    }

    override fun toString(): String {
        return "SedMottattMigreringRapportDto(rinaSaksnummer=" + this.getRinaSaksnummer() + ", dokumentId=" + this.getDokumentId() + ", journalpostId=" + this.getJournalpostId() + ")"
    }
}
