// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.controller.dto;

import no.nav.melosys.eessi.service.sed.helpers.LandkodeMapper;
import org.apache.commons.lang3.StringUtils;

public class Adresse {
    private String poststed;
    private String postnr;
    private String land;
    private String gateadresse;
    private String tilleggsnavn;
    private String region;
    private Adressetype adressetype;

    public static Adresse av(no.nav.melosys.eessi.models.sed.nav.Adresse adresseFraRina) {
        if (adresseFraRina == null) {
            return new Adresse();
        }
        Adresse adresse = new Adresse();
        adresse.poststed = adresseFraRina.getBy();
        adresse.postnr = adresseFraRina.getPostnummer();
        adresse.land = LandkodeMapper.mapTilNavLandkode(adresseFraRina.getLand());
        adresse.gateadresse = String.format("%s %s", StringUtils.defaultIfEmpty(adresseFraRina.getGate(), ""), StringUtils.defaultIfEmpty(adresseFraRina.getBygning(), "")).trim();
        adresse.tilleggsnavn = StringUtils.defaultIfEmpty(adresseFraRina.getBygning(), "");
        adresse.region = adresseFraRina.getRegion();
        adresse.adressetype = Adressetype.fraAdressetypeRina(adresseFraRina.getType());
        return adresse;
    }

    @java.lang.SuppressWarnings("all")
    public Adresse() {
    }

    @java.lang.SuppressWarnings("all")
    public String getPoststed() {
        return this.poststed;
    }

    @java.lang.SuppressWarnings("all")
    public String getPostnr() {
        return this.postnr;
    }

    @java.lang.SuppressWarnings("all")
    public String getLand() {
        return this.land;
    }

    @java.lang.SuppressWarnings("all")
    public String getGateadresse() {
        return this.gateadresse;
    }

    @java.lang.SuppressWarnings("all")
    public String getTilleggsnavn() {
        return this.tilleggsnavn;
    }

    @java.lang.SuppressWarnings("all")
    public String getRegion() {
        return this.region;
    }

    @java.lang.SuppressWarnings("all")
    public Adressetype getAdressetype() {
        return this.adressetype;
    }

    @java.lang.SuppressWarnings("all")
    public void setPoststed(final String poststed) {
        this.poststed = poststed;
    }

    @java.lang.SuppressWarnings("all")
    public void setPostnr(final String postnr) {
        this.postnr = postnr;
    }

    @java.lang.SuppressWarnings("all")
    public void setLand(final String land) {
        this.land = land;
    }

    @java.lang.SuppressWarnings("all")
    public void setGateadresse(final String gateadresse) {
        this.gateadresse = gateadresse;
    }

    @java.lang.SuppressWarnings("all")
    public void setTilleggsnavn(final String tilleggsnavn) {
        this.tilleggsnavn = tilleggsnavn;
    }

    @java.lang.SuppressWarnings("all")
    public void setRegion(final String region) {
        this.region = region;
    }

    @java.lang.SuppressWarnings("all")
    public void setAdressetype(final Adressetype adressetype) {
        this.adressetype = adressetype;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof Adresse)) return false;
        final Adresse other = (Adresse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$poststed = this.getPoststed();
        final java.lang.Object other$poststed = other.getPoststed();
        if (this$poststed == null ? other$poststed != null : !this$poststed.equals(other$poststed)) return false;
        final java.lang.Object this$postnr = this.getPostnr();
        final java.lang.Object other$postnr = other.getPostnr();
        if (this$postnr == null ? other$postnr != null : !this$postnr.equals(other$postnr)) return false;
        final java.lang.Object this$land = this.getLand();
        final java.lang.Object other$land = other.getLand();
        if (this$land == null ? other$land != null : !this$land.equals(other$land)) return false;
        final java.lang.Object this$gateadresse = this.getGateadresse();
        final java.lang.Object other$gateadresse = other.getGateadresse();
        if (this$gateadresse == null ? other$gateadresse != null : !this$gateadresse.equals(other$gateadresse))
            return false;
        final java.lang.Object this$tilleggsnavn = this.getTilleggsnavn();
        final java.lang.Object other$tilleggsnavn = other.getTilleggsnavn();
        if (this$tilleggsnavn == null ? other$tilleggsnavn != null : !this$tilleggsnavn.equals(other$tilleggsnavn))
            return false;
        final java.lang.Object this$region = this.getRegion();
        final java.lang.Object other$region = other.getRegion();
        if (this$region == null ? other$region != null : !this$region.equals(other$region)) return false;
        final java.lang.Object this$adressetype = this.getAdressetype();
        final java.lang.Object other$adressetype = other.getAdressetype();
        if (this$adressetype == null ? other$adressetype != null : !this$adressetype.equals(other$adressetype))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof Adresse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $poststed = this.getPoststed();
        result = result * PRIME + ($poststed == null ? 43 : $poststed.hashCode());
        final java.lang.Object $postnr = this.getPostnr();
        result = result * PRIME + ($postnr == null ? 43 : $postnr.hashCode());
        final java.lang.Object $land = this.getLand();
        result = result * PRIME + ($land == null ? 43 : $land.hashCode());
        final java.lang.Object $gateadresse = this.getGateadresse();
        result = result * PRIME + ($gateadresse == null ? 43 : $gateadresse.hashCode());
        final java.lang.Object $tilleggsnavn = this.getTilleggsnavn();
        result = result * PRIME + ($tilleggsnavn == null ? 43 : $tilleggsnavn.hashCode());
        final java.lang.Object $region = this.getRegion();
        result = result * PRIME + ($region == null ? 43 : $region.hashCode());
        final java.lang.Object $adressetype = this.getAdressetype();
        result = result * PRIME + ($adressetype == null ? 43 : $adressetype.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "Adresse(poststed=" + this.getPoststed() + ", postnr=" + this.getPostnr() + ", land=" + this.getLand() + ", gateadresse=" + this.getGateadresse() + ", tilleggsnavn=" + this.getTilleggsnavn() + ", region=" + this.getRegion() + ", adressetype=" + this.getAdressetype() + ")";
    }
}
