// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.controller.dto;

import java.util.Collection;
import java.util.Collections;

import no.nav.melosys.eessi.models.SedVedlegg;

public class OpprettBucOgSedDto {
    private SedDataDto sedDataDto;
    private Collection<SedVedlegg> vedlegg = Collections.emptySet();

    @java.lang.SuppressWarnings("all")
    public OpprettBucOgSedDto() {
    }

    @java.lang.SuppressWarnings("all")
    public SedDataDto getSedDataDto() {
        return this.sedDataDto;
    }

    @java.lang.SuppressWarnings("all")
    public Collection<SedVedlegg> getVedlegg() {
        return this.vedlegg;
    }

    @java.lang.SuppressWarnings("all")
    public void setSedDataDto(final SedDataDto sedDataDto) {
        this.sedDataDto = sedDataDto;
    }

    @java.lang.SuppressWarnings("all")
    public void setVedlegg(final Collection<SedVedlegg> vedlegg) {
        this.vedlegg = vedlegg;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof OpprettBucOgSedDto)) return false;
        final OpprettBucOgSedDto other = (OpprettBucOgSedDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$sedDataDto = this.getSedDataDto();
        final java.lang.Object other$sedDataDto = other.getSedDataDto();
        if (this$sedDataDto == null ? other$sedDataDto != null : !this$sedDataDto.equals(other$sedDataDto))
            return false;
        final java.lang.Object this$vedlegg = this.getVedlegg();
        final java.lang.Object other$vedlegg = other.getVedlegg();
        if (this$vedlegg == null ? other$vedlegg != null : !this$vedlegg.equals(other$vedlegg)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof OpprettBucOgSedDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $sedDataDto = this.getSedDataDto();
        result = result * PRIME + ($sedDataDto == null ? 43 : $sedDataDto.hashCode());
        final java.lang.Object $vedlegg = this.getVedlegg();
        result = result * PRIME + ($vedlegg == null ? 43 : $vedlegg.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "OpprettBucOgSedDto(sedDataDto=" + this.getSedDataDto() + ", vedlegg=" + this.getVedlegg() + ")";
    }
}
