// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.controller.dto;

import no.nav.melosys.eessi.models.FagsakRinasakKobling;

public class SaksrelasjonDto {
    private Long gsakSaksnummer;
    private String rinaSaksnummer;
    private String bucType;

    public static SaksrelasjonDto av(FagsakRinasakKobling fagsakRinasakKobling) {
        return new SaksrelasjonDto(fagsakRinasakKobling.getGsakSaksnummer(), fagsakRinasakKobling.getRinaSaksnummer(), fagsakRinasakKobling.getBucType().name());
    }

    @java.lang.SuppressWarnings("all")
    public Long getGsakSaksnummer() {
        return this.gsakSaksnummer;
    }

    @java.lang.SuppressWarnings("all")
    public String getRinaSaksnummer() {
        return this.rinaSaksnummer;
    }

    @java.lang.SuppressWarnings("all")
    public String getBucType() {
        return this.bucType;
    }

    @java.lang.SuppressWarnings("all")
    public void setGsakSaksnummer(final Long gsakSaksnummer) {
        this.gsakSaksnummer = gsakSaksnummer;
    }

    @java.lang.SuppressWarnings("all")
    public void setRinaSaksnummer(final String rinaSaksnummer) {
        this.rinaSaksnummer = rinaSaksnummer;
    }

    @java.lang.SuppressWarnings("all")
    public void setBucType(final String bucType) {
        this.bucType = bucType;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SaksrelasjonDto)) return false;
        final SaksrelasjonDto other = (SaksrelasjonDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$gsakSaksnummer = this.getGsakSaksnummer();
        final java.lang.Object other$gsakSaksnummer = other.getGsakSaksnummer();
        if (this$gsakSaksnummer == null ? other$gsakSaksnummer != null : !this$gsakSaksnummer.equals(other$gsakSaksnummer)) return false;
        final java.lang.Object this$rinaSaksnummer = this.getRinaSaksnummer();
        final java.lang.Object other$rinaSaksnummer = other.getRinaSaksnummer();
        if (this$rinaSaksnummer == null ? other$rinaSaksnummer != null : !this$rinaSaksnummer.equals(other$rinaSaksnummer)) return false;
        final java.lang.Object this$bucType = this.getBucType();
        final java.lang.Object other$bucType = other.getBucType();
        if (this$bucType == null ? other$bucType != null : !this$bucType.equals(other$bucType)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SaksrelasjonDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $gsakSaksnummer = this.getGsakSaksnummer();
        result = result * PRIME + ($gsakSaksnummer == null ? 43 : $gsakSaksnummer.hashCode());
        final java.lang.Object $rinaSaksnummer = this.getRinaSaksnummer();
        result = result * PRIME + ($rinaSaksnummer == null ? 43 : $rinaSaksnummer.hashCode());
        final java.lang.Object $bucType = this.getBucType();
        result = result * PRIME + ($bucType == null ? 43 : $bucType.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SaksrelasjonDto(gsakSaksnummer=" + this.getGsakSaksnummer() + ", rinaSaksnummer=" + this.getRinaSaksnummer() + ", bucType=" + this.getBucType() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public SaksrelasjonDto() {
    }

    @java.lang.SuppressWarnings("all")
    public SaksrelasjonDto(final Long gsakSaksnummer, final String rinaSaksnummer, final String bucType) {
        this.gsakSaksnummer = gsakSaksnummer;
        this.rinaSaksnummer = rinaSaksnummer;
        this.bucType = bucType;
    }
}
