// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.controller.dto;

import java.util.Comparator;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

@JsonIgnoreProperties(ignoreUnknown = true)
public class SedDataDto extends SedGrunnlagDto {
    private Bruker bruker;
    private Adresse kontaktadresse;
    private Adresse oppholdsadresse;
    private List<FamilieMedlem> familieMedlem;
    private Periode søknadsperiode;
    //A008 spesifikt
    private String avklartBostedsland;
    //A010, A009, A003 spesifikt
    private VedtakDto vedtakDto;
    //X008 spesifikt
    private InvalideringSedDto invalideringSedDto;
    //Lovvalg
    private List<Lovvalgsperiode> tidligereLovvalgsperioder;
    private Long gsakSaksnummer;
    private List<String> mottakerIder;
    private String ytterligereInformasjon;
    private SvarAnmodningUnntakDto svarAnmodningUnntak;
    private UtpekingAvvisDto utpekingAvvis;

    public Optional<String> finnLovvalgsland() {
        return getLovvalgsperioder().stream().map(Lovvalgsperiode::getLovvalgsland).filter(Objects::nonNull).findFirst();
    }

    public String finnLovvalgslandDefaultNO() {
        return finnLovvalgsland().orElse("NO");
    }

    public Optional<Lovvalgsperiode> finnLovvalgsperiode() {
        return getLovvalgsperioder().stream().max(Comparator.comparing(Lovvalgsperiode::getFom));
    }

    public boolean manglerAdresser() {
        return getBostedsadresse() == null && getKontaktadresse() == null && getOppholdsadresse() == null;
    }

    @java.lang.SuppressWarnings("all")
    public SedDataDto() {
    }

    @java.lang.SuppressWarnings("all")
    public Bruker getBruker() {
        return this.bruker;
    }

    @java.lang.SuppressWarnings("all")
    public Adresse getKontaktadresse() {
        return this.kontaktadresse;
    }

    @java.lang.SuppressWarnings("all")
    public Adresse getOppholdsadresse() {
        return this.oppholdsadresse;
    }

    @java.lang.SuppressWarnings("all")
    public List<FamilieMedlem> getFamilieMedlem() {
        return this.familieMedlem;
    }

    @java.lang.SuppressWarnings("all")
    public Periode getSøknadsperiode() {
        return this.søknadsperiode;
    }

    @java.lang.SuppressWarnings("all")
    public String getAvklartBostedsland() {
        return this.avklartBostedsland;
    }

    @java.lang.SuppressWarnings("all")
    public VedtakDto getVedtakDto() {
        return this.vedtakDto;
    }

    @java.lang.SuppressWarnings("all")
    public InvalideringSedDto getInvalideringSedDto() {
        return this.invalideringSedDto;
    }

    @java.lang.SuppressWarnings("all")
    public List<Lovvalgsperiode> getTidligereLovvalgsperioder() {
        return this.tidligereLovvalgsperioder;
    }

    @java.lang.SuppressWarnings("all")
    public Long getGsakSaksnummer() {
        return this.gsakSaksnummer;
    }

    @java.lang.SuppressWarnings("all")
    public List<String> getMottakerIder() {
        return this.mottakerIder;
    }

    @java.lang.SuppressWarnings("all")
    public String getYtterligereInformasjon() {
        return this.ytterligereInformasjon;
    }

    @java.lang.SuppressWarnings("all")
    public SvarAnmodningUnntakDto getSvarAnmodningUnntak() {
        return this.svarAnmodningUnntak;
    }

    @java.lang.SuppressWarnings("all")
    public UtpekingAvvisDto getUtpekingAvvis() {
        return this.utpekingAvvis;
    }

    @java.lang.SuppressWarnings("all")
    public void setBruker(final Bruker bruker) {
        this.bruker = bruker;
    }

    @java.lang.SuppressWarnings("all")
    public void setKontaktadresse(final Adresse kontaktadresse) {
        this.kontaktadresse = kontaktadresse;
    }

    @java.lang.SuppressWarnings("all")
    public void setOppholdsadresse(final Adresse oppholdsadresse) {
        this.oppholdsadresse = oppholdsadresse;
    }

    @java.lang.SuppressWarnings("all")
    public void setFamilieMedlem(final List<FamilieMedlem> familieMedlem) {
        this.familieMedlem = familieMedlem;
    }

    @java.lang.SuppressWarnings("all")
    public void setSøknadsperiode(final Periode søknadsperiode) {
        this.søknadsperiode = søknadsperiode;
    }

    @java.lang.SuppressWarnings("all")
    public void setAvklartBostedsland(final String avklartBostedsland) {
        this.avklartBostedsland = avklartBostedsland;
    }

    @java.lang.SuppressWarnings("all")
    public void setVedtakDto(final VedtakDto vedtakDto) {
        this.vedtakDto = vedtakDto;
    }

    @java.lang.SuppressWarnings("all")
    public void setInvalideringSedDto(final InvalideringSedDto invalideringSedDto) {
        this.invalideringSedDto = invalideringSedDto;
    }

    @java.lang.SuppressWarnings("all")
    public void setTidligereLovvalgsperioder(final List<Lovvalgsperiode> tidligereLovvalgsperioder) {
        this.tidligereLovvalgsperioder = tidligereLovvalgsperioder;
    }

    @java.lang.SuppressWarnings("all")
    public void setGsakSaksnummer(final Long gsakSaksnummer) {
        this.gsakSaksnummer = gsakSaksnummer;
    }

    @java.lang.SuppressWarnings("all")
    public void setMottakerIder(final List<String> mottakerIder) {
        this.mottakerIder = mottakerIder;
    }

    @java.lang.SuppressWarnings("all")
    public void setYtterligereInformasjon(final String ytterligereInformasjon) {
        this.ytterligereInformasjon = ytterligereInformasjon;
    }

    @java.lang.SuppressWarnings("all")
    public void setSvarAnmodningUnntak(final SvarAnmodningUnntakDto svarAnmodningUnntak) {
        this.svarAnmodningUnntak = svarAnmodningUnntak;
    }

    @java.lang.SuppressWarnings("all")
    public void setUtpekingAvvis(final UtpekingAvvisDto utpekingAvvis) {
        this.utpekingAvvis = utpekingAvvis;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "SedDataDto(bruker=" + this.getBruker() + ", kontaktadresse=" + this.getKontaktadresse() + ", oppholdsadresse=" + this.getOppholdsadresse() + ", familieMedlem=" + this.getFamilieMedlem() + ", søknadsperiode=" + this.getSøknadsperiode() + ", avklartBostedsland=" + this.getAvklartBostedsland() + ", vedtakDto=" + this.getVedtakDto() + ", invalideringSedDto=" + this.getInvalideringSedDto() + ", tidligereLovvalgsperioder=" + this.getTidligereLovvalgsperioder() + ", gsakSaksnummer=" + this.getGsakSaksnummer() + ", mottakerIder=" + this.getMottakerIder() + ", ytterligereInformasjon=" + this.getYtterligereInformasjon() + ", svarAnmodningUnntak=" + this.getSvarAnmodningUnntak() + ", utpekingAvvis=" + this.getUtpekingAvvis() + ")";
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof SedDataDto)) return false;
        final SedDataDto other = (SedDataDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (!super.equals(o)) return false;
        final java.lang.Object this$gsakSaksnummer = this.getGsakSaksnummer();
        final java.lang.Object other$gsakSaksnummer = other.getGsakSaksnummer();
        if (this$gsakSaksnummer == null ? other$gsakSaksnummer != null : !this$gsakSaksnummer.equals(other$gsakSaksnummer)) return false;
        final java.lang.Object this$bruker = this.getBruker();
        final java.lang.Object other$bruker = other.getBruker();
        if (this$bruker == null ? other$bruker != null : !this$bruker.equals(other$bruker)) return false;
        final java.lang.Object this$kontaktadresse = this.getKontaktadresse();
        final java.lang.Object other$kontaktadresse = other.getKontaktadresse();
        if (this$kontaktadresse == null ? other$kontaktadresse != null : !this$kontaktadresse.equals(other$kontaktadresse)) return false;
        final java.lang.Object this$oppholdsadresse = this.getOppholdsadresse();
        final java.lang.Object other$oppholdsadresse = other.getOppholdsadresse();
        if (this$oppholdsadresse == null ? other$oppholdsadresse != null : !this$oppholdsadresse.equals(other$oppholdsadresse)) return false;
        final java.lang.Object this$familieMedlem = this.getFamilieMedlem();
        final java.lang.Object other$familieMedlem = other.getFamilieMedlem();
        if (this$familieMedlem == null ? other$familieMedlem != null : !this$familieMedlem.equals(other$familieMedlem)) return false;
        final java.lang.Object this$søknadsperiode = this.getSøknadsperiode();
        final java.lang.Object other$søknadsperiode = other.getSøknadsperiode();
        if (this$søknadsperiode == null ? other$søknadsperiode != null : !this$søknadsperiode.equals(other$søknadsperiode)) return false;
        final java.lang.Object this$avklartBostedsland = this.getAvklartBostedsland();
        final java.lang.Object other$avklartBostedsland = other.getAvklartBostedsland();
        if (this$avklartBostedsland == null ? other$avklartBostedsland != null : !this$avklartBostedsland.equals(other$avklartBostedsland)) return false;
        final java.lang.Object this$vedtakDto = this.getVedtakDto();
        final java.lang.Object other$vedtakDto = other.getVedtakDto();
        if (this$vedtakDto == null ? other$vedtakDto != null : !this$vedtakDto.equals(other$vedtakDto)) return false;
        final java.lang.Object this$invalideringSedDto = this.getInvalideringSedDto();
        final java.lang.Object other$invalideringSedDto = other.getInvalideringSedDto();
        if (this$invalideringSedDto == null ? other$invalideringSedDto != null : !this$invalideringSedDto.equals(other$invalideringSedDto)) return false;
        final java.lang.Object this$tidligereLovvalgsperioder = this.getTidligereLovvalgsperioder();
        final java.lang.Object other$tidligereLovvalgsperioder = other.getTidligereLovvalgsperioder();
        if (this$tidligereLovvalgsperioder == null ? other$tidligereLovvalgsperioder != null : !this$tidligereLovvalgsperioder.equals(other$tidligereLovvalgsperioder)) return false;
        final java.lang.Object this$mottakerIder = this.getMottakerIder();
        final java.lang.Object other$mottakerIder = other.getMottakerIder();
        if (this$mottakerIder == null ? other$mottakerIder != null : !this$mottakerIder.equals(other$mottakerIder)) return false;
        final java.lang.Object this$ytterligereInformasjon = this.getYtterligereInformasjon();
        final java.lang.Object other$ytterligereInformasjon = other.getYtterligereInformasjon();
        if (this$ytterligereInformasjon == null ? other$ytterligereInformasjon != null : !this$ytterligereInformasjon.equals(other$ytterligereInformasjon)) return false;
        final java.lang.Object this$svarAnmodningUnntak = this.getSvarAnmodningUnntak();
        final java.lang.Object other$svarAnmodningUnntak = other.getSvarAnmodningUnntak();
        if (this$svarAnmodningUnntak == null ? other$svarAnmodningUnntak != null : !this$svarAnmodningUnntak.equals(other$svarAnmodningUnntak)) return false;
        final java.lang.Object this$utpekingAvvis = this.getUtpekingAvvis();
        final java.lang.Object other$utpekingAvvis = other.getUtpekingAvvis();
        if (this$utpekingAvvis == null ? other$utpekingAvvis != null : !this$utpekingAvvis.equals(other$utpekingAvvis)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof SedDataDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = super.hashCode();
        final java.lang.Object $gsakSaksnummer = this.getGsakSaksnummer();
        result = result * PRIME + ($gsakSaksnummer == null ? 43 : $gsakSaksnummer.hashCode());
        final java.lang.Object $bruker = this.getBruker();
        result = result * PRIME + ($bruker == null ? 43 : $bruker.hashCode());
        final java.lang.Object $kontaktadresse = this.getKontaktadresse();
        result = result * PRIME + ($kontaktadresse == null ? 43 : $kontaktadresse.hashCode());
        final java.lang.Object $oppholdsadresse = this.getOppholdsadresse();
        result = result * PRIME + ($oppholdsadresse == null ? 43 : $oppholdsadresse.hashCode());
        final java.lang.Object $familieMedlem = this.getFamilieMedlem();
        result = result * PRIME + ($familieMedlem == null ? 43 : $familieMedlem.hashCode());
        final java.lang.Object $søknadsperiode = this.getSøknadsperiode();
        result = result * PRIME + ($søknadsperiode == null ? 43 : $søknadsperiode.hashCode());
        final java.lang.Object $avklartBostedsland = this.getAvklartBostedsland();
        result = result * PRIME + ($avklartBostedsland == null ? 43 : $avklartBostedsland.hashCode());
        final java.lang.Object $vedtakDto = this.getVedtakDto();
        result = result * PRIME + ($vedtakDto == null ? 43 : $vedtakDto.hashCode());
        final java.lang.Object $invalideringSedDto = this.getInvalideringSedDto();
        result = result * PRIME + ($invalideringSedDto == null ? 43 : $invalideringSedDto.hashCode());
        final java.lang.Object $tidligereLovvalgsperioder = this.getTidligereLovvalgsperioder();
        result = result * PRIME + ($tidligereLovvalgsperioder == null ? 43 : $tidligereLovvalgsperioder.hashCode());
        final java.lang.Object $mottakerIder = this.getMottakerIder();
        result = result * PRIME + ($mottakerIder == null ? 43 : $mottakerIder.hashCode());
        final java.lang.Object $ytterligereInformasjon = this.getYtterligereInformasjon();
        result = result * PRIME + ($ytterligereInformasjon == null ? 43 : $ytterligereInformasjon.hashCode());
        final java.lang.Object $svarAnmodningUnntak = this.getSvarAnmodningUnntak();
        result = result * PRIME + ($svarAnmodningUnntak == null ? 43 : $svarAnmodningUnntak.hashCode());
        final java.lang.Object $utpekingAvvis = this.getUtpekingAvvis();
        result = result * PRIME + ($utpekingAvvis == null ? 43 : $utpekingAvvis.hashCode());
        return result;
    }
}
