// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.controller.dto;

import java.util.Arrays;

import org.springframework.util.StringUtils;

public enum SedStatus {
    SENDT("SENDT", "SENT"), UTKAST("UTKAST", "NEW"), TOM("TOM", "EMPTY"), MOTTATT("MOTTATT", "RECEIVED"), AVBRUTT("AVBRUTT", "CANCELLED");
    private final String norskStatus;
    private final String engelskStatus;

    SedStatus(String norskStatus, String engelskStatus) {
        this.engelskStatus = engelskStatus;
        this.norskStatus = norskStatus;
    }

    public static SedStatus fraNorskStatus(String norskStatus) {
        if (!StringUtils.hasText(norskStatus)) {
            return null;
        }
        return valueOf(norskStatus.toUpperCase());
    }

    public static SedStatus fraEngelskStatus(String engelskStatus) {
        if (!StringUtils.hasText(engelskStatus)) {
            return null;
        }
        return Arrays.stream(values()).filter(status -> engelskStatus.equalsIgnoreCase(status.engelskStatus)).findFirst().orElse(null);
    }

    public static boolean erGyldigEngelskStatus(String engelskstatus) {
        return MOTTATT.engelskStatus.equalsIgnoreCase(engelskstatus) || SENDT.engelskStatus.equalsIgnoreCase(engelskstatus);
    }

    @java.lang.SuppressWarnings("all")
    public String getNorskStatus() {
        return this.norskStatus;
    }

    @java.lang.SuppressWarnings("all")
    public String getEngelskStatus() {
        return this.engelskStatus;
    }
}
