// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.controller.dto;

import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.datatype.jsr310.deser.LocalDateDeserializer;
import com.fasterxml.jackson.datatype.jsr310.ser.LocalDateSerializer;

public class VedtakDto {
    @JsonDeserialize(using = LocalDateDeserializer.class)
    @JsonSerialize(using = LocalDateSerializer.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    private LocalDate datoForrigeVedtak;
    private boolean erFørstegangsvedtak;

    @java.lang.SuppressWarnings("all")
    public VedtakDto() {
    }

    @java.lang.SuppressWarnings("all")
    public LocalDate getDatoForrigeVedtak() {
        return this.datoForrigeVedtak;
    }

    @java.lang.SuppressWarnings("all")
    public boolean isErFørstegangsvedtak() {
        return this.erFørstegangsvedtak;
    }

    @JsonDeserialize(using = LocalDateDeserializer.class)
    @JsonFormat(shape = JsonFormat.Shape.STRING, pattern = "yyyy-MM-dd")
    @java.lang.SuppressWarnings("all")
    public void setDatoForrigeVedtak(final LocalDate datoForrigeVedtak) {
        this.datoForrigeVedtak = datoForrigeVedtak;
    }

    @java.lang.SuppressWarnings("all")
    public void setErFørstegangsvedtak(final boolean erFørstegangsvedtak) {
        this.erFørstegangsvedtak = erFørstegangsvedtak;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof VedtakDto)) return false;
        final VedtakDto other = (VedtakDto) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        if (this.isErFørstegangsvedtak() != other.isErFørstegangsvedtak()) return false;
        final java.lang.Object this$datoForrigeVedtak = this.getDatoForrigeVedtak();
        final java.lang.Object other$datoForrigeVedtak = other.getDatoForrigeVedtak();
        if (this$datoForrigeVedtak == null ? other$datoForrigeVedtak != null : !this$datoForrigeVedtak.equals(other$datoForrigeVedtak))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof VedtakDto;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + (this.isErFørstegangsvedtak() ? 79 : 97);
        final java.lang.Object $datoForrigeVedtak = this.getDatoForrigeVedtak();
        result = result * PRIME + ($datoForrigeVedtak == null ? 43 : $datoForrigeVedtak.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "VedtakDto(datoForrigeVedtak=" + this.getDatoForrigeVedtak() + ", erFørstegangsvedtak=" + this.isErFørstegangsvedtak() + ")";
    }
}
