// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.models.sed.medlemskap.impl;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import no.nav.melosys.eessi.models.sed.medlemskap.Medlemskap;
import no.nav.melosys.eessi.models.sed.nav.MeldingOmLovvalg;
import no.nav.melosys.eessi.models.sed.nav.Utsendingsland;
import no.nav.melosys.eessi.models.sed.nav.VedtakA010;

@JsonIgnoreProperties(ignoreUnknown = true)
public class MedlemskapA010 implements Medlemskap {
    private Utsendingsland andreland;
    private VedtakA010 vedtak;
    private MeldingOmLovvalg meldingomlovvalg;

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof MedlemskapA010)) return false;
        final MedlemskapA010 other = (MedlemskapA010) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$andreland = this.getAndreland();
        final java.lang.Object other$andreland = other.getAndreland();
        if (this$andreland == null ? other$andreland != null : !this$andreland.equals(other$andreland)) return false;
        final java.lang.Object this$vedtak = this.getVedtak();
        final java.lang.Object other$vedtak = other.getVedtak();
        if (this$vedtak == null ? other$vedtak != null : !this$vedtak.equals(other$vedtak)) return false;
        final java.lang.Object this$meldingomlovvalg = this.getMeldingomlovvalg();
        final java.lang.Object other$meldingomlovvalg = other.getMeldingomlovvalg();
        if (this$meldingomlovvalg == null ? other$meldingomlovvalg != null : !this$meldingomlovvalg.equals(other$meldingomlovvalg))
            return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof MedlemskapA010;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $andreland = this.getAndreland();
        result = result * PRIME + ($andreland == null ? 43 : $andreland.hashCode());
        final java.lang.Object $vedtak = this.getVedtak();
        result = result * PRIME + ($vedtak == null ? 43 : $vedtak.hashCode());
        final java.lang.Object $meldingomlovvalg = this.getMeldingomlovvalg();
        result = result * PRIME + ($meldingomlovvalg == null ? 43 : $meldingomlovvalg.hashCode());
        return result;
    }

    @java.lang.SuppressWarnings("all")
    public MedlemskapA010() {
    }

    @java.lang.SuppressWarnings("all")
    public Utsendingsland getAndreland() {
        return this.andreland;
    }

    @java.lang.SuppressWarnings("all")
    public VedtakA010 getVedtak() {
        return this.vedtak;
    }

    @java.lang.SuppressWarnings("all")
    public MeldingOmLovvalg getMeldingomlovvalg() {
        return this.meldingomlovvalg;
    }

    @java.lang.SuppressWarnings("all")
    public void setAndreland(final Utsendingsland andreland) {
        this.andreland = andreland;
    }

    @java.lang.SuppressWarnings("all")
    public void setVedtak(final VedtakA010 vedtak) {
        this.vedtak = vedtak;
    }

    @java.lang.SuppressWarnings("all")
    public void setMeldingomlovvalg(final MeldingOmLovvalg meldingomlovvalg) {
        this.meldingomlovvalg = meldingomlovvalg;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "MedlemskapA010(andreland=" + this.getAndreland() + ", vedtak=" + this.getVedtak() + ", meldingomlovvalg=" + this.getMeldingomlovvalg() + ")";
    }
}
