// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.dto;

public class PDLHentPersonResponse {
    private PDLPerson hentPerson;

    @java.lang.SuppressWarnings("all")
    public PDLHentPersonResponse() {
    }

    @java.lang.SuppressWarnings("all")
    public PDLPerson getHentPerson() {
        return this.hentPerson;
    }

    @java.lang.SuppressWarnings("all")
    public void setHentPerson(final PDLPerson hentPerson) {
        this.hentPerson = hentPerson;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PDLHentPersonResponse)) return false;
        final PDLHentPersonResponse other = (PDLHentPersonResponse) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$hentPerson = this.getHentPerson();
        final java.lang.Object other$hentPerson = other.getHentPerson();
        if (this$hentPerson == null ? other$hentPerson != null : !this$hentPerson.equals(other$hentPerson)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PDLHentPersonResponse;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $hentPerson = this.getHentPerson();
        result = result * PRIME + ($hentPerson == null ? 43 : $hentPerson.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PDLHentPersonResponse(hentPerson=" + this.getHentPerson() + ")";
    }
}
