// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.dto;

public class PDLKjoenn implements HarMetadata {
    private PDLKjoennType kjoenn;
    private PDLMetadata metadata;

    @java.lang.SuppressWarnings("all")
    public PDLKjoenn() {
    }

    @java.lang.SuppressWarnings("all")
    public PDLKjoennType getKjoenn() {
        return this.kjoenn;
    }

    @java.lang.SuppressWarnings("all")
    public PDLMetadata getMetadata() {
        return this.metadata;
    }

    @java.lang.SuppressWarnings("all")
    public void setKjoenn(final PDLKjoennType kjoenn) {
        this.kjoenn = kjoenn;
    }

    @java.lang.SuppressWarnings("all")
    public void setMetadata(final PDLMetadata metadata) {
        this.metadata = metadata;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PDLKjoenn)) return false;
        final PDLKjoenn other = (PDLKjoenn) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$kjoenn = this.getKjoenn();
        final java.lang.Object other$kjoenn = other.getKjoenn();
        if (this$kjoenn == null ? other$kjoenn != null : !this$kjoenn.equals(other$kjoenn)) return false;
        final java.lang.Object this$metadata = this.getMetadata();
        final java.lang.Object other$metadata = other.getMetadata();
        if (this$metadata == null ? other$metadata != null : !this$metadata.equals(other$metadata)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PDLKjoenn;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $kjoenn = this.getKjoenn();
        result = result * PRIME + ($kjoenn == null ? 43 : $kjoenn.hashCode());
        final java.lang.Object $metadata = this.getMetadata();
        result = result * PRIME + ($metadata == null ? 43 : $metadata.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PDLKjoenn(kjoenn=" + this.getKjoenn() + ", metadata=" + this.getMetadata() + ")";
    }
}
