// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.dto;

public final class PDLPaging {
    private final int pageNumber;
    private final int resultsPerPage;

    @java.lang.SuppressWarnings("all")
    public PDLPaging(final int pageNumber, final int resultsPerPage) {
        this.pageNumber = pageNumber;
        this.resultsPerPage = resultsPerPage;
    }

    @java.lang.SuppressWarnings("all")
    public int getPageNumber() {
        return this.pageNumber;
    }

    @java.lang.SuppressWarnings("all")
    public int getResultsPerPage() {
        return this.resultsPerPage;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PDLPaging)) return false;
        final PDLPaging other = (PDLPaging) o;
        if (this.getPageNumber() != other.getPageNumber()) return false;
        if (this.getResultsPerPage() != other.getResultsPerPage()) return false;
        return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        result = result * PRIME + this.getPageNumber();
        result = result * PRIME + this.getResultsPerPage();
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PDLPaging(pageNumber=" + this.getPageNumber() + ", resultsPerPage=" + this.getResultsPerPage() + ")";
    }
}
