// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.dto;

import java.util.HashMap;
import java.util.Map;

public final class PDLSokCriterion {
    private final String fieldName;
    private final Map<String, Object> searchRule;

    public static Builder fornavn() {
        return new Builder("person.navn.fornavn");
    }

    public static Builder etternavn() {
        return new Builder("person.navn.etternavn");
    }

    public static Builder fødselsdato() {
        return new Builder("person.foedsel.foedselsdato");
    }

    public static Builder statsborgerskap() {
        return new Builder("person.statsborgerskap.land");
    }


    public static class Builder {
        private final String feltNavn;
        private final Map<String, Object> søkeRegel;
        private static final String INNEHOLDER = "contains";
        private static final String ER_LIK = "equals";

        private Builder(String feltNavn) {
            this.feltNavn = feltNavn;
            this.søkeRegel = new HashMap<>();
        }

        public PDLSokCriterion inneholder(Object verdi) {
            søkeRegel.put(INNEHOLDER, verdi);
            return build();
        }

        public PDLSokCriterion erLik(Object verdi) {
            søkeRegel.put(ER_LIK, verdi);
            return build();
        }

        private PDLSokCriterion build() {
            return new PDLSokCriterion(feltNavn, søkeRegel);
        }
    }

    @java.lang.SuppressWarnings("all")
    public PDLSokCriterion(final String fieldName, final Map<String, Object> searchRule) {
        this.fieldName = fieldName;
        this.searchRule = searchRule;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PDLSokCriterion)) return false;
        final PDLSokCriterion other = (PDLSokCriterion) o;
        final java.lang.Object this$fieldName = this.getFieldName();
        final java.lang.Object other$fieldName = other.getFieldName();
        if (this$fieldName == null ? other$fieldName != null : !this$fieldName.equals(other$fieldName)) return false;
        final java.lang.Object this$searchRule = this.getSearchRule();
        final java.lang.Object other$searchRule = other.getSearchRule();
        if (this$searchRule == null ? other$searchRule != null : !this$searchRule.equals(other$searchRule)) return false;
        return true;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $fieldName = this.getFieldName();
        result = result * PRIME + ($fieldName == null ? 43 : $fieldName.hashCode());
        final java.lang.Object $searchRule = this.getSearchRule();
        result = result * PRIME + ($searchRule == null ? 43 : $searchRule.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PDLSokCriterion(fieldName=" + this.getFieldName() + ", searchRule=" + this.getSearchRule() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public String getFieldName() {
        return this.fieldName;
    }

    @java.lang.SuppressWarnings("all")
    public Map<String, Object> getSearchRule() {
        return this.searchRule;
    }
}
