// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.integration.pdl.dto;

public class PDLStatsborgerskap {
    private String land;

    @java.lang.SuppressWarnings("all")
    public PDLStatsborgerskap() {
    }

    @java.lang.SuppressWarnings("all")
    public String getLand() {
        return this.land;
    }

    @java.lang.SuppressWarnings("all")
    public void setLand(final String land) {
        this.land = land;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof PDLStatsborgerskap)) return false;
        final PDLStatsborgerskap other = (PDLStatsborgerskap) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$land = this.getLand();
        final java.lang.Object other$land = other.getLand();
        if (this$land == null ? other$land != null : !this$land.equals(other$land)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof PDLStatsborgerskap;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $land = this.getLand();
        result = result * PRIME + ($land == null ? 43 : $land.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "PDLStatsborgerskap(land=" + this.getLand() + ")";
    }
}
