name: Deploy T8

on:
  push:
    branches:
      - 'SPRINT-*'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Setup Maven
        uses: actions/cache@preview
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Create Docker tag
        env:
          NAME: melosys-eessi
        run: |
          echo "docker.pkg.github.com"/"$GITHUB_REPOSITORY"/"$NAME" > .docker_image
          echo "$(date "+%Y.%m.%d")-$(git rev-parse --short HEAD)" > .docker_tag
      - name: Test and build
        run: mvn clean package -B -e -U
      - name: Build docker image
        run: docker build . -t $(cat .docker_image):$(cat .docker_tag)
      - name: Push docker image
        run: |
          echo "$GITHUB_ACCESS_TOKEN" | docker login --username "x-access-token" --password-stdin https://docker.pkg.github.com
          docker push $(cat .docker_image):$(cat .docker_tag)
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
      - name: Deploy til t8
        uses: navikt/deployment-cli/action@0.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          AWAIT_SECONDS: 0
        with:
          cluster: dev-fss
          team: teammelosys
          resources: deploy/naiserator-t8.yaml