name: Deploy

on:
  push:
    #branches:
    #  - 'master'
    #  - 'SPRINT-*'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/melosys-eessi:${{ github.sha }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: What image
        run: echo $IMAGE
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11.x'
      - name: Setup Maven
        uses: actions/cache@preview
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Test and build
        run: mvn clean package -B -e -U
      - name: Build docker image
        run: |
          docker build -t ${IMAGE} .
      - name: Login to Github Package Registry
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
      - name: Push Docker image
        run: |
          docker push ${IMAGE}

  deploy_prod:
    name: Deploy til prod
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: prod-fss
          RESOURCE: deploy/nais.yaml
          VAR: namespace=default

  deploy_t8:
      name: Deploy til T8
      needs: build
      #if: contains(github.ref, 'SPRINT-')
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v1
        - name: Deploy
          uses: nais/deploy/actions/deploy@v1
          env:
            APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
            CLUSTER: dev-fss
            RESOURCE: deploy/nais.yaml
            VAR: namespace=t8
