// Generated by delombok at Thu Jul 04 12:27:09 CEST 2024
package no.nav.melosys.eessi.service.journalfoering;

public class DeltakerInformasjon {
    private String id;
    private String name;


    @java.lang.SuppressWarnings("all")
    public static class DeltakerInformasjonBuilder {
        @java.lang.SuppressWarnings("all")
        private String id;
        @java.lang.SuppressWarnings("all")
        private String name;

        @java.lang.SuppressWarnings("all")
        DeltakerInformasjonBuilder() {
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public DeltakerInformasjon.DeltakerInformasjonBuilder id(final String id) {
            this.id = id;
            return this;
        }

        /**
         * @return {@code this}.
         */
        @java.lang.SuppressWarnings("all")
        public DeltakerInformasjon.DeltakerInformasjonBuilder name(final String name) {
            this.name = name;
            return this;
        }

        @java.lang.SuppressWarnings("all")
        public DeltakerInformasjon build() {
            return new DeltakerInformasjon(this.id, this.name);
        }

        @java.lang.Override
        @java.lang.SuppressWarnings("all")
        public java.lang.String toString() {
            return "DeltakerInformasjon.DeltakerInformasjonBuilder(id=" + this.id + ", name=" + this.name + ")";
        }
    }

    @java.lang.SuppressWarnings("all")
    public static DeltakerInformasjon.DeltakerInformasjonBuilder builder() {
        return new DeltakerInformasjon.DeltakerInformasjonBuilder();
    }

    @java.lang.SuppressWarnings("all")
    public String getId() {
        return this.id;
    }

    @java.lang.SuppressWarnings("all")
    public String getName() {
        return this.name;
    }

    @java.lang.SuppressWarnings("all")
    public void setId(final String id) {
        this.id = id;
    }

    @java.lang.SuppressWarnings("all")
    public void setName(final String name) {
        this.name = name;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public boolean equals(final java.lang.Object o) {
        if (o == this) return true;
        if (!(o instanceof DeltakerInformasjon)) return false;
        final DeltakerInformasjon other = (DeltakerInformasjon) o;
        if (!other.canEqual((java.lang.Object) this)) return false;
        final java.lang.Object this$id = this.getId();
        final java.lang.Object other$id = other.getId();
        if (this$id == null ? other$id != null : !this$id.equals(other$id)) return false;
        final java.lang.Object this$name = this.getName();
        final java.lang.Object other$name = other.getName();
        if (this$name == null ? other$name != null : !this$name.equals(other$name)) return false;
        return true;
    }

    @java.lang.SuppressWarnings("all")
    protected boolean canEqual(final java.lang.Object other) {
        return other instanceof DeltakerInformasjon;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public int hashCode() {
        final int PRIME = 59;
        int result = 1;
        final java.lang.Object $id = this.getId();
        result = result * PRIME + ($id == null ? 43 : $id.hashCode());
        final java.lang.Object $name = this.getName();
        result = result * PRIME + ($name == null ? 43 : $name.hashCode());
        return result;
    }

    @java.lang.Override
    @java.lang.SuppressWarnings("all")
    public java.lang.String toString() {
        return "DeltakerInformasjon(id=" + this.getId() + ", name=" + this.getName() + ")";
    }

    @java.lang.SuppressWarnings("all")
    public DeltakerInformasjon() {
    }

    @java.lang.SuppressWarnings("all")
    public DeltakerInformasjon(final String id, final String name) {
        this.id = id;
        this.name = name;
    }
}
